# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, nodejs, stdenv, fetchurl, writeText, git, cacert, writeShellApplication }:
{ src, overrideAttrs ? null, ... } @ args:

let

  yarnPath = ./../../../../../Users/clansty/Projects/SmsForwarderClient/.yarn/releases/yarn-3.5.1.cjs;
  lockfile = ./../../../../../Users/clansty/Projects/SmsForwarderClient/yarn.lock;
  cacheFolder = ".yarn/cache";

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs ];
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    npm_config_build_from_source = "true";
    # Defines the shell alias to run Yarn.
    postHook = ''
      yarn() {
        CI=1 node "${yarnPath}" "$@"
      }
    '';
  };

  # Create derivations for fetching dependencies.
  cacheDrvs = let
    builder = builtins.toFile "builder.sh" ''
      source $stdenv/setup
      cd "$src"
      HOME="$TMP" yarn_cache_folder="$TMP" CI=1 \
        node '${yarnPath}' nixify fetch-one $locator
      # Because we change the cache dir, Yarn may generate a different name.
      mv "$TMP/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
    '';
  in lib.mapAttrs (locator: { filename, sha512 }: stdenv.mkDerivation {
    inherit src builder locator;
    name = lib.strings.sanitizeDerivationName locator;
    buildInputs = [ nodejs git cacert ];
    outputFilename = filename;
    outputHashMode = "flat";
    outputHashAlgo = "sha512";
    outputHash = sha512;
  }) cacheEntries;

  # Create a shell snippet to copy dependencies from a list of derivations.
  mkCacheBuilderForDrvs = drvs:
    writeText "collect-cache.sh" (lib.concatMapStrings (drv: ''
      cp ${drv} '${drv.outputFilename}'
    '') drvs);


  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "qwq";
    # Disable Nixify plugin to save on some unnecessary processing.
    yarn_enable_nixify = "false";

    configurePhase = ''
      # Copy over the Yarn cache.
      rm -fr '${cacheFolder}'
      mkdir -p '${cacheFolder}'
      pushd '${cacheFolder}' > /dev/null
      source ${mkCacheBuilderForDrvs (lib.attrValues cacheDrvs)}
      popd > /dev/null

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure



      # Run normal Yarn install to complete dependency installation.
      yarn install --immutable --immutable-cache

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p "$out/libexec/$name" "$out/bin"

      # Move the package contents to the output directory.
      # - If the package.json has a `files` field, only files matching those patterns are copied
      # - Otherwise all files are copied
      yarn pack --out package.tgz
      tar xzvf package.tgz --directory "$out/libexec/$name" --strip-components=1

      cp .yarnrc* "$out/libexec/$name"
      cp --recursive .yarn "$out/libexec/$name"

      # If the project uses the node-modules linker, then
      # include the node_modules folder in the package.
      if [ -d node_modules ]; then
        cp --recursive node_modules "$out/libexec/$name"
      else
        # Otherwise, assume PnP. Copy the loader into the package.
        cp .pnp.* "$out/libexec/$name"
      fi

      cd "$out/libexec/$name"

      # Invoke a plugin internal command to setup binaries.
      yarn nixify install-bin $out/bin

      # A package with node_modules doesn't need the cache
      if [ -d node_modules ]; then
        yarn cache clean
      fi

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
      yarn = writeShellApplication {
        name = "yarn";
        runtimeInputs = [ nodejs ];
        text = ''
          ${yarnPath} --cwd ${project}/libexec/${project.name} "$@"
        '';
      };
    };
  });

cacheEntries = {
"vfonts@npm:0.0.3" = { filename = "vfonts-npm-0.0.3-654cafce8d-02928c65b4.zip"; sha512 = "02928c65b481da61873abfd8a3697ad20ea20c2f280c13c9f449c51e2493d0b5d6aa1eab7be93401759e3f33962992642d5175dbf3e872e4bebc70e2a6bef5fe"; };
"typescript@npm:5.1.6" = { filename = "typescript-npm-5.1.6-b157762de3-b2f2c35096.zip"; sha512 = "b2f2c35096035fe1f5facd1e38922ccb8558996331405eb00a5111cc948b2e733163cc22fab5db46992aba7dd520fff637f2c1df4996ff0e134e77d3249a7350"; };
"vite-svg-loader@npm:4.0.0" = { filename = "vite-svg-loader-npm-4.0.0-613b09fc70-2363054b33.zip"; sha512 = "2363054b33ee26baf440a43bc9f301dec4c7a89b37f00539546b2cb75ef883ec311cdf990d9d3010870d776974f8c52961ca459cd90fdf3969501840ca631feb"; };
"@vitejs/plugin-vue-jsx@npm:3.0.1" = { filename = "@vitejs-plugin-vue-jsx-npm-3.0.1-f334bdb7de-5b25811a9f.zip"; sha512 = "5b25811a9f7c54c0e68eb348bcacb611901cfcf0a834798731c697d3006e6f6b6526206ded711a2e8afb7428bb1feb7251f7e1c4f45263349690c0f30038db11"; };
"sass@npm:1.65.1" = { filename = "sass-npm-1.65.1-d6fc30b338-33e325fc80.zip"; sha512 = "33e325fc80cd07489992e0814cd4929496f87493ffe78c423c2dbafa5746a574e6f3bde20c2a3e4ea47b16ee3d6bc5afcf1d36b405227b829d6c4c9ddcc7f8e2"; };
"@marcoschulte/vue3-progress@npm:0.0.7" = { filename = "@marcoschulte-vue3-progress-npm-0.0.7-066b7f2212-47c6d4cb97.zip"; sha512 = "47c6d4cb97e3d7f6256355d8e87bd87b98b7ecb3d9d24de88d8a1d7ec1ca8ac789c66392a7978cdd07741ef0c2a2ec30496a807d0d518cc779d16833ef5cdb4b"; };
"@vueuse/core@npm:10.3.0" = { filename = "@vueuse-core-npm-10.3.0-447a53ed02-54af7ab9f2.zip"; sha512 = "54af7ab9f2aff8cc795dfc9d846aa9a27dc0949d7a6eec79697819e7dc8cb17b1682f267e7501382afa45736b6877363e640e381b7ac1fd6bc18dc860911afd8"; };
"vite@npm:4.4.9" = { filename = "vite-npm-4.4.9-e845c1bbf8-c511024cea.zip"; sha512 = "c511024ceae39c68c7dbf2ac4381ee655cd7bb62cf43867a14798bc835d3320b8fa7867a336143c30825c191c1fb4e9aa3348fce831ab617e96203080d3d2908"; };
"vue@npm:3.3.4" = { filename = "vue-npm-3.3.4-174fadbea4-58b6c62a66.zip"; sha512 = "58b6c62a66a375ce5df460fcb7ba41b37c8637c635faf06ef472ae4197f412cf9ad83586cd8e3f66c486404fbe8550e694f90ff724a571d1ba78830791099c59"; };
"immutable@npm:4.0.0" = { filename = "immutable-npm-4.0.0-74b844f82e-4b5e9181e4.zip"; sha512 = "4b5e9181e4d5fa06728a481835ec09c86367e5d03268666c95b522b7644ab891098022e4479a43c4c81a68f2ed82f10751ce5d33e208d7b873b6e7f9dfaf4d87"; };
"source-map-js@npm:1.0.2" = { filename = "source-map-js-npm-1.0.2-ee4f9f9b30-c049a7fc4d.zip"; sha512 = "c049a7fc4deb9a7e9b481ae3d424cc793cb4845daa690bc5a05d428bf41bf231ced49b4cf0c9e77f9d42fdb3d20d6187619fc586605f5eabe995a316da8d377c"; };
"@types/web-bluetooth@npm:0.0.17" = { filename = "@types-web-bluetooth-npm-0.0.17-d325201882-8c72ba8cd1.zip"; sha512 = "8c72ba8cd1d7abd3fcab608e1d8eb828420df23f67d783f1282d4a747f995e91a0c861f92fa195e9423edb22bb34854452028f8a68148a593b35915635a4f4db"; };
"@vueuse/metadata@npm:10.3.0" = { filename = "@vueuse-metadata-npm-10.3.0-fd8300ee70-fb5cb1ff73.zip"; sha512 = "fb5cb1ff730129ddd831e37cd6e7fed2ebc12211ed63c5075ecef7311852063a8eb152bb213459e36f7b69711f8da35835e2c0ece018c43700febf591ed96937"; };
"vue-demi@npm:0.14.5" = { filename = "vue-demi-npm-0.14.5-6e9e31189b-ff44b9372b.zip"; sha512 = "ff44b9372b8224590514252a2f73363cced6062205f9628a6b130dccb80e2023d55cd9d1da94aeb68d5539b7ea9eedcecf88ab281a3a9ff48b8db4c5366b9643"; };
"@vueuse/shared@npm:10.3.0" = { filename = "@vueuse-shared-npm-10.3.0-c31e599756-2392ce5c79.zip"; sha512 = "2392ce5c798ff2aa09c82de11fef3a6cc1eb3d198598e0f19f803645003003e06c90bc4cde5367200f8458a31344edcd4ab571b84a4f7d21ee8083b9309c9bf3"; };
"rollup@npm:3.28.0" = { filename = "rollup-npm-3.28.0-4ab1b4022e-6ded4a0d3c.zip"; sha512 = "6ded4a0d3ca531d68e82897d5eebaa9d085014a062620bc328f2859ccf78d6a148a51ed53f1275a5f89b55cc6d7b1440b7cee44e5a9e3a51442f809b4b26f727"; };
"@vue/shared@npm:3.3.4" = { filename = "@vue-shared-npm-3.3.4-76d250afa2-12fe53ff81.zip"; sha512 = "12fe53ff816bfa29ea53f89212067a86512c626b8d30149ff28b36705820f6150e1fb4e4e46897ad9eddb1d1cfc02d8941053939910eed69a905f7a5509baabe"; };
"fsevents@npm:2.3.2" = { filename = "fsevents-npm-2.3.2-a881d6ac9f-97ade64e75.zip"; sha512 = "97ade64e75091afee5265e6956cb72ba34db7819b4c3e94c431d4be2b19b8bb7a2d4116da417950c3425f17c8fe693d25e20212cac583ac1521ad066b77ae31f"; };
"typescript@patch:typescript@npm%3A5.1.6#~builtin<compat/typescript>::version=5.1.6&hash=77c9e2" = { filename = "typescript-patch-9812310e38-21e88b0a0c.zip"; sha512 = "21e88b0a0c0226f9cb9fd25b9626fb05b4c0f3fddac521844a13e1f30beb8f14e90bd409a9ac43c812c5946d714d6e0dee12d5d02dfc1c562c5aacfa1f49b606"; };
"@babel/plugin-transform-typescript@npm:7.21.3" = { filename = "@babel-plugin-transform-typescript-npm-7.21.3-d5850c9640-c16fd577bf.zip"; sha512 = "c16fd577bf43f633deb76fca2a8527d8ae25968c8efdf327c1955472c3e0257e62992473d1ad7f9ee95379ce2404699af405ea03346055adadd3478ad0ecd117"; };
"postcss@npm:8.4.27" = { filename = "postcss-npm-8.4.27-2a9f5f8f40-1cdd0c2988.zip"; sha512 = "1cdd0c298849df6cd65f7e646a3ba36870a37b65f55fd59d1a165539c263e9b4872a402bf4ed1ca1bc31f58b68b2835545e33ea1a23b161a1f8aa6d5ded81e78"; };
"@vue/compiler-dom@npm:3.3.4" = { filename = "@vue-compiler-dom-npm-3.3.4-029250af79-1c2ac0c89d.zip"; sha512 = "1c2ac0c89de8eef7be1c568d57504e6245adaaec40c2c4d9717bc231ca10bf682d918a3b358d24c786eeaf8e0d7eb8a65f57d9044775a304783fde1d069a1896"; };
"@vue/server-renderer@npm:3.3.4" = { filename = "@vue-server-renderer-npm-3.3.4-75b963f24d-e8598ed1a4.zip"; sha512 = "e8598ed1a44df70edaea0ad6786aea6443b9b3d9266249eec5690401859d72d45a1e29ba3eef20e37a95f020abd5e763088b79070ee848af436a4390a253a37a"; };
"svgo@npm:3.0.2" = { filename = "svgo-npm-3.0.2-c4a041dc0f-381ba14aa7.zip"; sha512 = "381ba14aa782e71ab7033227634a3041c11fa3e2769aeaf0df43a08a615de61925108e34f55af6e7c5146f4a3109e78deabb4fa9d687e36d45d1f848b4e23d17"; };
"@vue/runtime-dom@npm:3.3.4" = { filename = "@vue-runtime-dom-npm-3.3.4-554b8c4277-dac9ada7f6.zip"; sha512 = "dac9ada7f6128bcccc031fe5c25d00db94ffb7c011fcb70bada22fa4d889ff842eeb139ab9304bcc52cb5ae9030911a52cb3510b691bb190bbe5fab680b4411a"; };
"@babel/helper-plugin-utils@npm:7.21.5" = { filename = "@babel-helper-plugin-utils-npm-7.21.5-b310faa7aa-6f086e9a84.zip"; sha512 = "6f086e9a84a50ea7df0d5639c8f9f68505af510ea3258b3c8ac8b175efdfb7f664436cb48996f71791a1350ba68f47ad3424131e8e718c5e2ad45564484cbb36"; };
"chokidar@npm:3.5.3" = { filename = "chokidar-npm-3.5.3-c5f9b0a56a-b49fcde401.zip"; sha512 = "b49fcde40176ba007ff361b198a2d35df60d9bb2a5aab228279eb810feae9294a6b4649ab15981304447afe1e6ffbf4788ad5db77235dc770ab777c6e771980c"; };
"nanoid@npm:3.3.6" = { filename = "nanoid-npm-3.3.6-e6d6ae7e71-7d0eda6570.zip"; sha512 = "7d0eda657002738aa5206107bd0580aead6c95c460ef1bdd0b1a87a9c7ae6277ac2e9b945306aaa5b32c6dcb7feaf462d0f552e7f8b5718abfc6ead5c94a71b3"; };
"picocolors@npm:1.0.0" = { filename = "picocolors-npm-1.0.0-d81e0b1927-a2e8092dd8.zip"; sha512 = "a2e8092dd86c8396bdba9f2b5481032848525b3dc295ce9b57896f931e63fc16f79805144321f72976383fc249584672a75cc18d6777c6b757603f372f745981"; };
"@babel/helper-annotate-as-pure@npm:7.18.6" = { filename = "@babel-helper-annotate-as-pure-npm-7.18.6-36e25293d8-88ccd15ced.zip"; sha512 = "88ccd15ced475ef2243fdd3b2916a29ea54c5db3cd0cfabf9d1d29ff6e63b7f7cd1c27264137d7a40ac2e978b9b9a542c332e78f40eb72abe737a7400788fc1b"; };
"@babel/plugin-syntax-typescript@npm:7.21.4" = { filename = "@babel-plugin-syntax-typescript-npm-7.21.4-bcb1097f7e-a59ce2477b.zip"; sha512 = "a59ce2477b7ae8c8945dc37dda292fef9ce46a6507b3d76b03ce7f3a6c9451a6567438b20a78ebcb3955d04095fd1ccd767075a863f79fcc30aa34dcfa441fe0"; };
"@vue/babel-plugin-jsx@npm:1.1.1" = { filename = "@vue-babel-plugin-jsx-npm-1.1.1-bdeeeaa2ec-2887c041fb.zip"; sha512 = "2887c041fbd9dcefeca26811a8d3a21835fca50b0e87a3c0a50bd7a4289339ee316426a4066648bad67e090186404457828d46e023eb820aa6865d99b99c4002"; };
"@vue/compiler-sfc@npm:3.3.4" = { filename = "@vue-compiler-sfc-npm-3.3.4-783aff746b-0a0adfdd3e.zip"; sha512 = "0a0adfdd3e812f528e25e4b3bbf14b2296b719a8aac609eca42035295527cc253b918a552dc15218e917efef26b7ca94054dc8784a1a18c06c3d4bb4d18ab8b9"; };
"@trysound/sax@npm:0.2.0" = { filename = "@trysound-sax-npm-0.2.0-9f763d0295-11226c39b5.zip"; sha512 = "11226c39b52b391719a2a92e10183e4260d9651f86edced166da1d95f39a0a1eaa470e44d14ac685ccd6d3df7e2002433782872c0feeb260d61e80f21250e65c"; };
"commander@npm:7.2.0" = { filename = "commander-npm-7.2.0-19178180f8-53501cbeee.zip"; sha512 = "53501cbeee61d5157546c0bef0fedb6cdfc763a882136284bed9a07225f09a14b82d2a84e7637edfd1a679fb35ed9502fd58ef1d091e6287f60d790147f68ddc"; };
"csstype@npm:3.1.2" = { filename = "csstype-npm-3.1.2-cead7d99b2-e1a52e6c25.zip"; sha512 = "e1a52e6c25c1314d6beef5168da704ab29c5186b877c07d822bd0806717d9a265e8493a2e35ca7e68d0f5d472d43fac1cdce70fd79fd0853dff81f3028d857b5"; };
"csso@npm:5.0.5" = { filename = "csso-npm-5.0.5-b21e2a8b65-0ad858d36b.zip"; sha512 = "0ad858d36bf5012ed243e9ec69962a867509061986d2ee07cc040a4b26e4d062c00d4c07e5ba8d430706ceb02dd87edd30a52b5937fd45b1b6f2119c4993d59a"; };
"@vue/compiler-ssr@npm:3.3.4" = { filename = "@vue-compiler-ssr-npm-3.3.4-9c5036c29f-5d1875d55e.zip"; sha512 = "5d1875d55ea864080dd90e5d81a29f93308e312faf00163db5b391b38c2fe799fd3eb58955823dc632f2f8bdd271a4534cc0020646b7f82717be1a8d30dc16e7"; };
"naive-ui@npm:2.34.4" = { filename = "naive-ui-npm-2.34.4-00b9952d24-0e91d9208e.zip"; sha512 = "0e91d9208ec362f53bd23571db6a1b4a213bbbd225330e788b0e8610d06628de46df19c068c098b8d57ac3fbe53dbbc8ce25c89e4790c2d852130a23be504d52"; };
"css-tree@npm:2.3.1" = { filename = "css-tree-npm-2.3.1-6540d78e26-493cc24b5c.zip"; sha512 = "493cc24b5c22b05ee5314b8a0d72d8a5869491c1458017ae5ed75aeb6c3596637dbe1b11dac2548974624adec9f7a1f3a6cf40593dc1f9185eb0e8279543fbc0"; };
"@vue/runtime-core@npm:3.3.4" = { filename = "@vue-runtime-core-npm-3.3.4-4a56fcce5e-d402da5126.zip"; sha512 = "d402da51269658cba5d857d65fbe322121160bcb1a6fcf03601d5183705e92505c6e90418f491a331ca3e27628f457a6ca7158b9add25f5b0cf5cf53664b8011"; };
"normalize-path@npm:3.0.0" = { filename = "normalize-path-npm-3.0.0-658ba7d77f-88eeb4da89.zip"; sha512 = "88eeb4da891e10b1318c4b2476b6e2ecbeb5ff97d946815ffea7794c31a89017c70d7f34b3c2ebf23ef4e9fc9fb99f7dffe36da22011b5b5c6ffa34f4873ec20"; };
"@vue/compiler-core@npm:3.3.4" = { filename = "@vue-compiler-core-npm-3.3.4-e514bded25-5437942ea6.zip"; sha512 = "5437942ea6575b316c9cd84f4f128a44939713da8b6958060e152c599e6d771d5db056c398d7574ee706ff8092e0d99ac4f14e7eef8712a8dd923d2323201b9e"; };
"@vue/babel-helper-vue-transform-on@npm:1.0.2" = { filename = "@vue-babel-helper-vue-transform-on-npm-1.0.2-37a3cad896-5a03d293ad.zip"; sha512 = "5a03d293ad8841d276c86cc1071f3bcd3e8d47571e5f9a8ca1c0147a7a8c50c65768fc416140b5edda7d429bdd8e8ab1bf52ff010540e61015ac3f0cd6da6f4e"; };
"camelcase@npm:6.3.0" = { filename = "camelcase-npm-6.3.0-e5e42a0d15-8c96818a90.zip"; sha512 = "8c96818a9076434998511251dcb2761a94817ea17dbdc37f47ac080bd088fc62c7369429a19e2178b993497132c8cbcf5cc1f44ba963e76782ba469c0474938d"; };
"html-tags@npm:3.1.0" = { filename = "html-tags-npm-3.1.0-2be8f49b1e-67587f2d40.zip"; sha512 = "67587f2d4022390d7bc34b1313773ecb0b0e0c79fb331aa3e20023eb4c862c7188a1ff775d126fcd75f4e4f08f956666a1c57688c4d24d85a77f9d4b1a42f345"; };
"svg-tags@npm:1.0.0" = { filename = "svg-tags-npm-1.0.0-68a35c11fa-407e5ef87c.zip"; sha512 = "407e5ef87cfa2fb81c61d738081c2decd022ce13b922d035b214b49810630bf5d1409255a4beb3a940b77b32f6957806deff16f1bf0ce1ab11c7a184115a0b7f"; };
"braces@npm:3.0.2" = { filename = "braces-npm-3.0.2-782240b28a-e2a8e769a8.zip"; sha512 = "e2a8e769a863f3d4ee887b5fe21f63193a891c68b612ddb4b68d82d1b5f3ff9073af066c343e9867a393fe4c2555dcb33e89b937195feb9c1613d259edfcd459"; };
"glob-parent@npm:5.1.2" = { filename = "glob-parent-npm-5.1.2-021ab32634-f4f2bfe242.zip"; sha512 = "f4f2bfe2425296e8a47e36864e4f42be38a996db40420fe434565e4480e3322f18eb37589617a98640c5dc8fdec1a387007ee18dbb1f3f5553409c34d17f425e"; };
"is-binary-path@npm:2.1.0" = { filename = "is-binary-path-npm-2.1.0-e61d46f557-84192eb88c.zip"; sha512 = "84192eb88cff70d320426f35ecd63c3d6d495da9d805b19bc65b518984b7c0760280e57dbf119b7e9be6b161784a5a673ab2c6abe83abb5198a432232ad5b35c"; };
"is-glob@npm:4.0.3" = { filename = "is-glob-npm-4.0.3-cb87bf1bdb-d381c1319f.zip"; sha512 = "d381c1319fcb69d341cc6e6c7cd588e17cd94722d9a32dbd60660b993c4fb7d0f19438674e68dfec686d09b7c73139c9166b47597f846af387450224a8101ab4"; };
"readdirp@npm:3.6.0" = { filename = "readdirp-npm-3.6.0-f950cc74ab-1ced032e6e.zip"; sha512 = "1ced032e6e45670b6d7352d71d21ce7edf7b9b928494dcaba6f11fba63180d9da6cd7061ebc34175ffda6ff529f481818c962952004d273178acd70f7059b320"; };
"estree-walker@npm:2.0.2" = { filename = "estree-walker-npm-2.0.2-dfab42f65c-6151e6f982.zip"; sha512 = "6151e6f9828abe2259e57f5fd3761335bb0d2ebd76dc1a01048ccee22fabcfef3c0859300f6d83ff0d1927849368775ec5a6d265dde2f6de5a1be1721cd94efc"; };
"fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=df0bf1" = { filename = "fsevents-patch-2882183fbf-8.zip"; sha512 = "edbd0fd80be379c14409605f77e52fdc78a119e17f875e8b90a220c3e5b29e54a1477c21d91fd30b957ea4866406dc3ff87b61432d2840ff8866b309e5866140"; };
"@babel/helper-module-imports@npm:7.16.7" = { filename = "@babel-helper-module-imports-npm-7.16.7-19c74fd92b-ddd2c4a600.zip"; sha512 = "ddd2c4a600a2e9a4fee192ab92bf35a627c5461dbab4af31b903d9ba4d6b6e59e0ff3499fde4e2e9a0eebe24906f00b636f8b4d9bd72ff24d50e6618215c3212"; };
"@babel/plugin-syntax-jsx@npm:7.16.7" = { filename = "@babel-plugin-syntax-jsx-npm-7.16.7-06e2646d53-cd9b0e53c5.zip"; sha512 = "cd9b0e53c50e8ddb0afaf0f42e0b221a94e4f59aee32a591364266a31195c48cac5fef288d02c1c935686bda982d2e0f1ed61cceb995fc9f6fb09ef5ebecdd2b"; };
"anymatch@npm:3.1.2" = { filename = "anymatch-npm-3.1.2-1d5471acfa-985163db22.zip"; sha512 = "985163db2292fac9e5a1e072bf99f1b5baccf196e4de25a0b0b81865ebddeb3b3eb4480734ef0a2ac8c002845396b91aa89121f5b84f93981a4658164a9ec6e9"; };
"@babel/parser@npm:7.21.8" = { filename = "@babel-parser-npm-7.21.8-2fefc717c4-1b9a820fed.zip"; sha512 = "1b9a820fedfb6ef179e6ffa1dbc080808882949dec68340a616da2aa354af66ea2886bd68e61bd444d270aa0b24ad6273e3cfaf17d6878c34bf2521becacb353"; };
"magic-string@npm:0.30.0" = { filename = "magic-string-npm-0.30.0-20d8e0b6e4-7bdf22e273.zip"; sha512 = "7bdf22e27334d8a393858a16f5f840af63a7c05848c000fd714da5aa5eefa09a1bc01d8469362f25cc5c4a14ec01b46557b7fff8751365522acddf21e57c488d"; };
"css-select@npm:5.1.0" = { filename = "css-select-npm-5.1.0-9365a79de5-2772c049b1.zip"; sha512 = "2772c049b188d3b8a8159907192e926e11824aea525b8282981f72ba3f349cf9ecd523fdf7734875ee2cb772246c22117fc062da105b6d59afe8dcd5c99c9bda"; };
"@babel/core@npm:7.21.8" = { filename = "@babel-core-npm-7.21.8-236525e651-f281184473.zip"; sha512 = "f28118447355af2a90bd340e2e60699f94c8020517eba9b71bf8ebff62fa9e00d63f076e033f9dfb97548053ad62ada45fafb0d96584b1a90e8aef5a3b8241b1"; };
"@babel/types@npm:7.16.8" = { filename = "@babel-types-npm-7.16.8-68f858fd51-4f6a187b29.zip"; sha512 = "4f6a187b2924df70e21d6e6c0822f91b1b936fe060bc92bb477b93bd8a712c88fe41a73f85c0ec53b033353374fe33e773b04ffc340ad36afd8f647dd05c4ee1"; };
"@css-render/plugin-bem@npm:0.15.11" = { filename = "@css-render-plugin-bem-npm-0.15.11-71d4d4d96c-835370f343.zip"; sha512 = "835370f343fb8b843b0879354e9b3af926675e019bd1c68d3b1d3e3a6a72be035565ae56c9f112f32d336debdc436020ee56abb4e17ecee2b6105e9043abe2d5"; };
"@css-render/vue3-ssr@npm:0.15.11" = { filename = "@css-render-vue3-ssr-npm-0.15.11-5dabe69966-c8a01f5b58.zip"; sha512 = "c8a01f5b58af9eeec9274fc570564014f823495fc36d820b0e83354bf2549513589da238a0f84285ff6fd79884fa0172aeafa5c557c31d75cbb72ba3b524f7a2"; };
"@types/katex@npm:0.14.0" = { filename = "@types-katex-npm-0.14.0-acd5bc3e87-330e0d0337.zip"; sha512 = "330e0d0337ba48c87f5b793965fbad673653789bf6e50dfe8d726a7b0cbefd37195055e31503aae629814aa79447e4f23a4b87ad1ac565c0d9a9d9978836f39b"; };
"@types/lodash@npm:4.14.182" = { filename = "@types-lodash-npm-4.14.182-1073aac722-7dd137aa9d.zip"; sha512 = "7dd137aa9dbabd632408bd37009d984655164fa1ecc3f2b6eb94afe35bf0a5852cbab6183148d883e9c73a958b7fec9a9bcf7c8e45d41195add6a18c34958209"; };
"async-validator@npm:4.0.7" = { filename = "async-validator-npm-4.0.7-c351309693-c4a764fb7f.zip"; sha512 = "c4a764fb7f7bb1e777a9e47d0b405cf9add9db017793363ebdeb3d6f3e6f19bf0b4256a710a76d357ae18acdae102b3c3e0fbde8d72cc27eca7ce27ea439c3f7"; };
"date-fns-tz@npm:1.3.3" = { filename = "date-fns-tz-npm-1.3.3-4b42de3dcf-52111dffb4.zip"; sha512 = "52111dffb44f9f419df00b325ed510b8d4723190cb47e2efaaf9704c2dc510f39d5f9c32263bff9599c5218f31a9c7775731bd8a9365d3ce6042059897110101"; };
"date-fns@npm:2.28.0" = { filename = "date-fns-npm-2.28.0-c19c5add1b-a0516b2e4f.zip"; sha512 = "a0516b2e4f99b8bffc6cc5193349f185f195398385bdcaf07f17c2c4a24473c99d933eb0018be4142a86a6d46cb0b06be6440ad874f15e795acbedd6fd727a1f"; };
"evtd@npm:0.2.4" = { filename = "evtd-npm-0.2.4-c15e36763d-1f9151a077.zip"; sha512 = "1f9151a077c83c0f63df40a1b4e6d844616b502e60950b0e08674f05fed3257ca64afd71d1e24e4d8f55e7d8c32fe8e1797d87b2d2b14e1237be159010330ec1"; };
"highlight.js@npm:11.5.1" = { filename = "highlight.js-npm-11.5.1-0fb1167640-bff556101d.zip"; sha512 = "bff556101d7691c6275ad19318e368fc971cd0621ef3d86222f5373df7d8191a2fc1ffd47f118138cbcf85e5fe91cfeefaecd6184f49a3ec18090955efc9edef"; };
"lodash-es@npm:4.17.21" = { filename = "lodash-es-npm-4.17.21-b45832dfce-05cbffad6e.zip"; sha512 = "05cbffad6e2adbb331a4e16fbd826e7faee403a1a04873b82b42c0f22090f280839f85b95393f487c1303c8a3d2a010048bf06151a6cbe03eee4d388fb0a12d2"; };
"lodash@npm:4.17.21" = { filename = "lodash-npm-4.17.21-6382451519-eb835a2e51.zip"; sha512 = "eb835a2e51d381e561e508ce932ea50a8e5a68f4ebdd771ea240d3048244a8d13658acbd502cd4829768c56f2e16bdd4340b9ea141297d472517b83868e677f7"; };
"seemly@npm:0.3.6" = { filename = "seemly-npm-0.3.6-87ae398976-56d0472d99.zip"; sha512 = "56d0472d992ff0e679d191941bffd80c1782ebba53cb4435f942431de6e083c50db4784b4d98771c45b704b79ebe17ea34f8cf6b20eda767f363513e1e5c3f08"; };
"treemate@npm:0.3.11" = { filename = "treemate-npm-0.3.11-7be66c23fc-0c6ccbc6c5.zip"; sha512 = "0c6ccbc6c5ce7faf27f5f48669c4734aa93ba4064a77f1324af02779aab6333986f6b32748aafe8de1ba99da8f8d9a027fe9c7c1d5389b4768edb5fc6a77fca2"; };
"mdn-data@npm:2.0.30" = { filename = "mdn-data-npm-2.0.30-bf7b39c09a-d6ac5ac743.zip"; sha512 = "d6ac5ac7439a1607df44b22738ecf83f48e66a0874e4482d6424a61c52da5cde5750f1d1229b6f5fa1b80a492be89465390da685b11f97d62b8adcc6e88189aa"; };
"@babel/types@npm:7.19.0" = { filename = "@babel-types-npm-7.19.0-8c9f82c2b5-9b346715a6.zip"; sha512 = "9b346715a68aeede70ba9c685a144b0b26c53bcd595d448e24c8fa8df4d5956a5712e56ebadb7c85dcc32f218ee42788e37b93d50d3295c992072224cb3ef3fe"; };
"@babel/template@npm:7.16.7" = { filename = "@babel-template-npm-7.16.7-a18e444be8-10cd112e89.zip"; sha512 = "10cd112e89276e00f8b11b55a51c8b2f1262c318283a980f4d6cdb0286dc05734b9aaeeb9f3ad3311900b09bc913e02343fcaa9d4a4f413964aaab04eb84ac4a"; };
"@types/lodash-es@npm:4.17.6" = { filename = "@types-lodash-es-npm-4.17.6-fd5abbdc74-9bd239dd52.zip"; sha512 = "9bd239dd525086e278821949ce12fbdd4f100a060fed9323fc7ad5661113e1641f28a7ebab617230ed3474680d8f4de705c1928b48252bb684be6ec9eed715db"; };
"vdirs@npm:0.1.8" = { filename = "vdirs-npm-0.1.8-59a32a98d6-a7be8ccad3.zip"; sha512 = "a7be8ccad3e72f2891150d53085b8f924cc9d9a9e474cd58827e81417e8feef7f5a8ecbb00efa7631592bf5b3be0a0fa40da41789fcf18dab2cec2bddd01ea47"; };
"vooks@npm:0.2.12" = { filename = "vooks-npm-0.2.12-0d1a2d856b-e6841ec5b6.zip"; sha512 = "e6841ec5b6cb3938ce3ba0822a209fc4fd9cbb18af7e5034a979f3a80a6f6cfcdadc402bf8992ddffe09a5796c746731b7f6c3366c4a2e8309278f657ae8ea18"; };
"postcss@npm:8.4.5" = { filename = "postcss-npm-8.4.5-675038f8bb-b78abdd89c.zip"; sha512 = "b78abdd89c10f7b48f4bdcd376104a19d6e9c7495ab521729bdb3df315af6c211360e9f06887ad3bc0ab0f61a04b91d68ea11462997c79cced58b9ccd66fac07"; };
"css-tree@npm:2.2.1" = { filename = "css-tree-npm-2.2.1-ee98ac48a8-b94aa8cc2f.zip"; sha512 = "b94aa8cc2f09e6f66c91548411fcf74badcbad3e150345074715012d16333ce573596ff5dfca03c2a87edf1924716db765120f94247e919d72753628ba3aba27"; };
"@vue/reactivity@npm:3.3.4" = { filename = "@vue-reactivity-npm-3.3.4-4bb841d3a9-81c3d0c587.zip"; sha512 = "81c3d0c587d23656a57a7a31afb51357274f6512b51baffc67cda183b2361a7e65e646029c26a8bc28587f26b65bba808dcd93cdd3bacab48d2b99d11ad0ec97"; };
"node-gyp@npm:8.4.1" = { filename = "node-gyp-npm-8.4.1-13c90a9c9b-341710b5da.zip"; sha512 = "341710b5da39d3660e6a886b37e210d33f8282047405c2e62c277bcc744c7552c5b8b972ebc3a7d5c2813794e60cc48c3ebd142c46d6e0321db4db6c92dd0355"; };
"@babel/helper-create-class-features-plugin@npm:7.21.8" = { filename = "@babel-helper-create-class-features-plugin-npm-7.21.8-c10fd51753-26b978bd2e.zip"; sha512 = "26b978bd2e741259c0f4a1cc37521ad58728c50d28fe2fc8041d4381497e13a0b686a10e170246855eaf3af08886862e9d93fc27994ef914e13fca0d73efdcb8"; };
"binary-extensions@npm:2.2.0" = { filename = "binary-extensions-npm-2.2.0-180c33fec7-ccd267956c.zip"; sha512 = "ccd267956c58d2315f5d3ea6757cf09863c5fc703e50fbeb13a7dc849b812ef76e3cf9ca8f35a0c48498776a7478d7b4a0418e1e2b8cb9cb9731f2922aaad7f8"; };
"is-extglob@npm:2.1.1" = { filename = "is-extglob-npm-2.1.1-0870ea68b5-df033653d0.zip"; sha512 = "df033653d06d0eb567461e58a7a8c9f940bd8c22274b94bf7671ab36df5719791aae15eef6d83bbb5e23283967f2f984b8914559d4449efda578c775c4be6f85"; };
"picomatch@npm:2.3.1" = { filename = "picomatch-npm-2.3.1-c782cfd986-050c865ce8.zip"; sha512 = "050c865ce81119c4822c45d3c84f1ced46f93a0126febae20737bd05ca20589c564d6e9226977df859ed5e03dc73f02584a2b0faad36e896936238238b0446cf"; };
"@babel/helper-plugin-utils@npm:7.16.7" = { filename = "@babel-helper-plugin-utils-npm-7.16.7-9e572698e0-d08dd86554.zip"; sha512 = "d08dd86554a186c2538547cd537552e4029f704994a9201d41d82015c10ed7f58f9036e8d1527c3760f042409163269d308b0b3706589039c5f1884619c6d4ce"; };
"css-render@npm:0.15.11" = { filename = "css-render-npm-0.15.11-82d52bcf9a-1d05cad944.zip"; sha512 = "1d05cad94477d1b03bece39dc5afb6ecfcee70e4cd8ce5a893e479536745fd44c11d763cf1e76cc69a511e05237bc1f4f87067eaec6d3120a1a3321f4ccdcfa5"; };
"fill-range@npm:7.0.1" = { filename = "fill-range-npm-7.0.1-b8b1817caa-cc283f4e65.zip"; sha512 = "cc283f4e65b504259e64fd969bcf4def4eb08d85565e906b7d36516e87819db52029a76b6363d0f02d0d532f0033c9603b9e2d943d56ee3b0d4f7ad3328ff917"; };
"@vue/reactivity-transform@npm:3.3.4" = { filename = "@vue-reactivity-transform-npm-3.3.4-bfbf394bf7-b425e78b20.zip"; sha512 = "b425e78b2084ac7037887fbe012dcad5e5963ac9714ae15a04fda1c6766ec8c53ef231de1cfdc4d3cf46bd5d84bfec8ebdccf48da4ff5ee2f4b5084e54f0a1b1"; };
"@jridgewell/sourcemap-codec@npm:1.4.15" = { filename = "@jridgewell-sourcemap-codec-npm-1.4.15-a055fb62cf-b881c7e503.zip"; sha512 = "b881c7e503db3fc7f3c1f35a1dd2655a188cc51a3612d76efc8a6eb74728bef5606e6758ee77423e564092b4a518aba569bbb21c9bac5ab7a35b0c6ae7e344c8"; };
"boolbase@npm:1.0.0" = { filename = "boolbase-npm-1.0.0-965fe9af6d-3e25c80ef6.zip"; sha512 = "3e25c80ef626c3a3487c73dbfc70ac322ec830666c9ad915d11b701142fab25ec1e63eff2c450c74347acfd2de854ccde865cd79ef4db1683f7c7b046ea43bb0"; };
"css-what@npm:6.1.0" = { filename = "css-what-npm-6.1.0-57f751efbb-b975e547e1.zip"; sha512 = "b975e547e1e90b79625918f84e67db5d33d896e6de846c9b584094e529f0c63e2ab85ee33b9daffd05bff3a146a1916bec664e18bb76dd5f66cbff9fc13b2bbe"; };
"gensync@npm:1.0.0-beta.2" = { filename = "gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip"; sha512 = "a7437e58c6be12aa6c90f7730eac7fa9833dc78872b4ad2963d2031b00a3367a93f98aec75f9aaac7220848e4026d67a8655e870b24f20a543d103c0d65952ec"; };
"json5@npm:2.2.3" = { filename = "json5-npm-2.2.3-9962c55073-2a7436a933.zip"; sha512 = "2a7436a93393830bce797d4626275152e37e877b265e94ca69c99e3d20c2b9dab021279146a39cdb700e71b2dd32a4cebd1514cd57cee102b1af906ce5040349"; };
"semver@npm:6.3.0" = { filename = "semver-npm-6.3.0-b3eace8bfd-1b26ecf6db.zip"; sha512 = "1b26ecf6db9e8292dd90df4e781d91875c0dcc1b1909e70f5d12959a23c7eebb8f01ea581c00783bbee72ceeaad9505797c381756326073850dc36ed284b21b9"; };
"@babel/helper-validator-identifier@npm:7.16.7" = { filename = "@babel-helper-validator-identifier-npm-7.16.7-8599fb00fc-dbb3db9d18.zip"; sha512 = "dbb3db9d184343152520a209b5684f5e0ed416109cde82b428ca9c759c29b10c7450657785a8b5c5256aa74acc6da491c1f0cf6b784939f7931ef82982051b69"; };
"to-fast-properties@npm:2.0.0" = { filename = "to-fast-properties-npm-2.0.0-0dc60cc481-be2de62fe5.zip"; sha512 = "be2de62fe58ead94e3e592680052683b1ec986c72d589e7b21e5697f8744cdbf48c266fa72f6c15932894c10187b5f54573a3bcf7da0bfd964d5caf23d436168"; };
"domhandler@npm:5.0.3" = { filename = "domhandler-npm-5.0.3-3ede73dc10-0f58f4a6af.zip"; sha512 = "0f58f4a6af63e6f3a4320aa446d28b5790a009018707bce2859dcb1d21144c7876482b5188395a188dfa974238c019e0a1e610d2fc269a12b2c192ea2b0b131c"; };
"nth-check@npm:2.1.1" = { filename = "nth-check-npm-2.1.1-f97afc8169-5afc3dafcd.zip"; sha512 = "5afc3dafcd1573b08877ca8e6148c52abd565f1d06b1eb08caf982e3fa289a82f2cae697ffb55b5021e146d60443f1590a5d6b944844e944714a5b549675bcd3"; };
"@babel/code-frame@npm:7.21.4" = { filename = "@babel-code-frame-npm-7.21.4-5db83e65be-e5390e6ec1.zip"; sha512 = "e5390e6ec1ac58dcef01d4f18eaf1fd2f1325528661ff6d4a5de8979588b9f5a8e852a54a91b923846f7a5c681b217f0a45c2524eb9560553160cd963b7d592c"; };
"convert-source-map@npm:1.8.0" = { filename = "convert-source-map-npm-1.8.0-037f671dde-985d974a2d.zip"; sha512 = "985d974a2d33e1a2543ada51c93e1ba2f73eaed608dc39f229afc78f71dcc4c8b7d7c684aa647e3c6a3a204027444d69e53e169ce94e8d1fa8d7dee80c9c8fed"; };
"debug@npm:4.3.3" = { filename = "debug-npm-4.3.3-710fd4cc7f-14472d56fe.zip"; sha512 = "14472d56fe4a94dbcfaa6dbed2dd3849f1d72ba78104a1a328047bb564643ca49df0224c3a17fa63533fd11dd3d4c8636cd861191232a2c6735af00cc2d4de16"; };
"@babel/helper-string-parser@npm:7.18.10" = { filename = "@babel-helper-string-parser-npm-7.18.10-cf6fe67f9a-d554a43933.zip"; sha512 = "d554a4393365b624916b5c00a4cc21c990c6617e7f3fe30be7d9731f107f12c33229a7a3db9d829bfa110d2eb9f04790745d421640e3bd245bb412dc0ea123c1"; };
"@babel/helper-validator-identifier@npm:7.19.1" = { filename = "@babel-helper-validator-identifier-npm-7.19.1-d84f19e1dc-0eca5e86a7.zip"; sha512 = "0eca5e86a729162af569b46c6c41a63e18b43dbe09fda1d2a3c8924f7d617116af39cac5e4cd5d431bb760b4dca3c0970e0c444789b1db42bcf1fa41fbad0a3a"; };
"@types/lodash@npm:4.14.178" = { filename = "@types-lodash-npm-4.14.178-5433b9ed68-a69a04a60b.zip"; sha512 = "a69a04a60bfc5257c3130a554b4efa0c383f0141b7b3db8ab7cf07ad2a46ea085fce66d0242da41da7e5647b133d5dfb2c15add9cbed8d7fef955e4a1e5b3128"; };
"evtd@npm:0.2.3" = { filename = "evtd-npm-0.2.3-51a4edcda1-5ddded6263.zip"; sha512 = "5ddded626355bf97c62e9b0a99aa2187b74e90b50032c06e2e75723250a152ad5b57bbca844fc07d3bd0b9f22f8dfe96ae4c68614efe5f879a4191c3c8070b5a"; };
"nanoid@npm:3.2.0" = { filename = "nanoid-npm-3.2.0-27f7f3aa52-3d1d5a69fe.zip"; sha512 = "3d1d5a69fea84e538057cf64106e713931c4ef32af344068ecff153ff91252f39b0f2b472e09b0dfff43ac3cf520c92938d90e6455121fe93976e23660f4fccc"; };
"mdn-data@npm:2.0.28" = { filename = "mdn-data-npm-2.0.28-9e644d5992-f51d587a6e.zip"; sha512 = "f51d587a6ebe8e426c3376c74ea6df3e19ec8241ed8e2466c9c8a3904d5d04397199ea4f15b8d34d14524b5de926d8724ae85207984be47e165817c26e49e0aa"; };
"env-paths@npm:2.2.1" = { filename = "env-paths-npm-2.2.1-7c7577428c-65b5df55a8.zip"; sha512 = "65b5df55a8bab92229ab2b40dad3b387fad24613263d103a97f91c9fe43ceb21965cd3392b1ccb5d77088021e525c4e0481adb309625d0cb94ade1d1fb8dc17e"; };
"graceful-fs@npm:4.2.9" = { filename = "graceful-fs-npm-4.2.9-ee48e00aaa-68ea4e07ff.zip"; sha512 = "68ea4e07ff2c041ada184f9278b830375f8e0b75154e3f080af6b70f66172fabb4108d19b3863a96b53fc068a310b9b6493d86d1291acc5f3861eb4b79d26ad6"; };
"@ampproject/remapping@npm:2.2.1" = { filename = "@ampproject-remapping-npm-2.2.1-3da3d624be-03c04fd526.zip"; sha512 = "03c04fd526acc64a1f4df22651186f3e5ef0a9d6d6530ce4482ec9841269cf7a11dbb8af79237c282d721c5312024ff17529cd72cc4768c11e999b58e2302079"; };
"@babel/helper-environment-visitor@npm:7.21.5" = { filename = "@babel-helper-environment-visitor-npm-7.21.5-7d7d1d1996-e436af7b62.zip"; sha512 = "e436af7b62956e919066448013a3f7e2cd0b51010c26c50f790124dcd350be81d5597b4e6ed0a4a42d098a27de1e38561cd7998a116a42e7899161192deac9a6"; };
"@babel/code-frame@npm:7.16.7" = { filename = "@babel-code-frame-npm-7.16.7-093eb9e124-db2f7faa31.zip"; sha512 = "db2f7faa31bc2c9cf63197b481b30ea57147a5fc1a6fab60e5d6c02cdfbf6de8e17b5121f99917b3dabb5eeb572da078312e70697415940383efc140d4e0808b"; };
"@babel/parser@npm:7.16.12" = { filename = "@babel-parser-npm-7.16.12-427f7b1500-af287f0f3d.zip"; sha512 = "af287f0f3dfa564958a7dddfeb62e08c0de9ce9bd8447fcde0997da26ec477bf19f37161b9d970e2c7e0d1f77e441258907d3347beddd0d42cae85ed46947703"; };
"domutils@npm:3.1.0" = { filename = "domutils-npm-3.1.0-66c92ef7eb-e5757456dd.zip"; sha512 = "e5757456ddd173caa411cfc02c2bb64133c65546d2c4081381a3bafc8a57411a41eed70494551aa58030be9e58574fcc489828bebd673863d39924fb4878f416"; };
"nopt@npm:5.0.0" = { filename = "nopt-npm-5.0.0-304b40fbfe-d35fdec187.zip"; sha512 = "d35fdec187269503843924e0114c0c6533fb54bbf1620d0f28b4b60ba01712d6687f62565c55cc20a504eff0fbe5c63e22340c3fad549ad40469ffb611b04f2f"; };
"rimraf@npm:3.0.2" = { filename = "rimraf-npm-3.0.2-2cb7dac69a-87f4164e39.zip"; sha512 = "87f4164e396f0171b0a3386cc1877a817f572148ee13a7e113b238e48e8a9f2f31d009a92ec38a591ff1567d9662c6b67fd8818a2dbbaed74bc26a87a2a4a9a0"; };
"semver@npm:7.3.5" = { filename = "semver-npm-7.3.5-618cf5db6a-5eafe6102b.zip"; sha512 = "5eafe6102bea2a7439897c1856362e31cc348ccf96efd455c8b5bc2c61e6f7e7b8250dc26b8828c1d76a56f818a7ee907a36ae9fb37a599d3d24609207001d60"; };
"which@npm:2.0.2" = { filename = "which-npm-2.0.2-320ddf72f7-1a5c563d3c.zip"; sha512 = "1a5c563d3c1b52d5f893c8b61afe11abc3bab4afac492e8da5bde69d550de701cf9806235f20a47b5c8fa8a1d6a9135841de2596535e998027a54589000e66d1"; };
"@babel/helpers@npm:7.21.5" = { filename = "@babel-helpers-npm-7.21.5-86b407bd6a-a6f74b8579.zip"; sha512 = "a6f74b8579713988e7f5adf1a986d8b5255757632ba65b2552f0f609ead5476edb784044c7e4b18f3681ee4818ca9d08c41feb9bd4e828648c25a00deaa1f9e4"; };
"@babel/template@npm:7.20.7" = { filename = "@babel-template-npm-7.20.7-c157fc5838-2eb1a0ab8d.zip"; sha512 = "2eb1a0ab8d415078776bceb3473d07ab746e6bb4c2f6ca46ee70efb284d75c4a32bb0cd6f4f4946dec9711f9c0780e8e5d64b743208deac6f8e9858afadc349e"; };
"@babel/types@npm:7.21.5" = { filename = "@babel-types-npm-7.21.5-3c8c157928-43242a99c6.zip"; sha512 = "43242a99c612d13285ee4af46cc0f1066bcb6ffd38307daef7a76e8c70f36cfc3255eb9e75c8e768b40e761176c313aec4d5c0b9d97a21e494d49d5fd123a9f7"; };
"@babel/helper-member-expression-to-functions@npm:7.21.5" = { filename = "@babel-helper-member-expression-to-functions-npm-7.21.5-ffc2fec35d-c404b4a027.zip"; sha512 = "c404b4a0271c640b7dc8c34af7b683c70a43200259e02330cfc02e79e6b271e9227f35554cd6ad015eabcfa1fea75b9d0b87b69f3d1e6c2af6edd224060b1732"; };
"@babel/helper-optimise-call-expression@npm:7.18.6" = { filename = "@babel-helper-optimise-call-expression-npm-7.18.6-65705387c4-e518fe8418.zip"; sha512 = "e518fe8418571405e21644cfb39cf694f30b6c47b10b006609a92469ae8b8775cbff56f0b19732343e2ea910641091c5a2dc73b56ceba04e116a33b0f8bd2fbd"; };
"@babel/helper-skip-transparent-expression-wrappers@npm:7.20.0" = { filename = "@babel-helper-skip-transparent-expression-wrappers-npm-7.20.0-3370bb1f83-34da8c832d.zip"; sha512 = "34da8c832d1c8a546e45d5c1d59755459ffe43629436707079989599b91e8c19e50e73af7a4bd09c95402d389266731b0d9c5f69e372d8ebd3a709c05c80d7dd"; };
"@babel/helper-split-export-declaration@npm:7.18.6" = { filename = "@babel-helper-split-export-declaration-npm-7.18.6-53ebf8ad4c-c6d3dede53.zip"; sha512 = "c6d3dede53878f6be1d869e03e9ffbbb36f4897c7cc1527dc96c56d127d834ffe4520a6f7e467f5b6f3c2843ea0e81a7819d66ae02f707f6ac057f3d57943a2b"; };
"@emotion/hash@npm:0.8.0" = { filename = "@emotion-hash-npm-0.8.0-0104f4bbf3-4b35d88a97.zip"; sha512 = "4b35d88a97e67275c1d990c96d3b0450451d089d1508619488fc0acb882cb1ac91e93246d471346ebd1b5402215941ef4162efe5b51534859b39d8b3a0e3ffaa"; };
"@types/node@npm:17.0.25" = { filename = "@types-node-npm-17.0.25-cd1a2f2374-6a820bd624.zip"; sha512 = "6a820bd624e69ea772f52a6cdb326484eff5829443dc981939373929ade109f58c21698b9f0a831bd6ceea799e722a75dc49c5fa7a6bc32a81e1cbdfc6507b64"; };
"csstype@npm:3.0.10" = { filename = "csstype-npm-3.0.10-e26ef49bb2-20a8fa324f.zip"; sha512 = "20a8fa324f2b33ddf94aa7507d1b6ab3daa6f3cc308888dc50126585d7952f2471de69b2dbe0635d1fdc31223fef8e070842691877e725caf456e2378685a631"; };
"vueuc@npm:0.4.51" = { filename = "vueuc-npm-0.4.51-794074113f-7969659fac.zip"; sha512 = "7969659facd8a1f7b7676bf5629d00a4830a648c279f3632c711ceedf8f7d7f6c8f61546a2dec74e2f2ff91e9185dcd76136bef7ae6eeac38bb1c6129840cfac"; };
"@babel/generator@npm:7.21.5" = { filename = "@babel-generator-npm-7.21.5-576849ce71-78af737b9d.zip"; sha512 = "78af737b9dd701d4c657f9731880430fa1c177767b562f4e8a330a7fe72a4abe857e3d24de4e6d9dafc1f6a11f894162d27e523d7e5948ff9e3925a0ce9867c4"; };
"@babel/helper-function-name@npm:7.21.0" = { filename = "@babel-helper-function-name-npm-7.21.0-a17ce5a05a-d63e63c3e0.zip"; sha512 = "d63e63c3e0e3e8b3138fa47b0cd321148a300ef12b8ee951196994dcd2a492cc708aeda94c2c53759a5c9177fffaac0fd8778791286746f72a000976968daf4e"; };
"@babel/traverse@npm:7.16.10" = { filename = "@babel-traverse-npm-7.16.10-25c7c5da49-58f52314f8.zip"; sha512 = "58f52314f8a02157cd3004712e703e6b22dff57cee4bc1ab1954c511c6f885fd7763ea68d2d5f006891bc7b77b1f2e9c8c7cb0354f580c8343d5559ed971d087"; };
"to-regex-range@npm:5.0.1" = { filename = "to-regex-range-npm-5.0.1-f1e8263b00-f76fa01b3d.zip"; sha512 = "f76fa01b3d5be85db6a2a143e24df9f60dd047d151062d0ba3df62953f2f697b16fe5dad9b0ac6191c7efc7b1d9dcaa4b768174b7b29da89d4428e64bc0a20ed"; };
"domelementtype@npm:2.3.0" = { filename = "domelementtype-npm-2.3.0-02de7cbfba-ee837a318f.zip"; sha512 = "ee837a318ff702622f383409d1f5b25dd1024b692ef64d3096ff702e26339f8e345820f29a68bcdcea8cfee3531776b3382651232fbeae95612d6f0a75efb4f6"; };
"esbuild@npm:0.18.20" = { filename = "esbuild-npm-0.18.20-004a76d281-5d253614e5.zip"; sha512 = "5d253614e50cdb6ec22095afd0c414f15688e7278a7eb4f3720a6dd1306b0909cf431e7b9437a90d065a31b1c57be60130f63fe3e8d0083b588571f31ee6ec7b"; };
"@babel/helper-compilation-targets@npm:7.21.5" = { filename = "@babel-helper-compilation-targets-npm-7.21.5-999fc74b3f-0edecb9c97.zip"; sha512 = "0edecb9c970ddc22ebda1163e77a7f314121bef9e483e0e0d9a5802540eed90d5855b6bf9bce03419b35b2e07c323e62d0353b153fa1ca34f17dbba897a83c25"; };
"safe-buffer@npm:5.1.2" = { filename = "safe-buffer-npm-5.1.2-c27fedf6c4-f2f1f7943c.zip"; sha512 = "f2f1f7943ca44a594893a852894055cf619c1fbcb611237fc39e461ae751187e7baf4dc391a72125e0ac4fb2d8c5c0b3c71529622e6a58f46b960211e704903c"; };
"ms@npm:2.1.2" = { filename = "ms-npm-2.1.2-ec0c1512ff-673cdb2c31.zip"; sha512 = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f"; };
"npmlog@npm:6.0.0" = { filename = "npmlog-npm-6.0.0-94a534434f-33d8a7fe3d.zip"; sha512 = "33d8a7fe3d63bf83b16655b6588ae7ba10b5f37b067a661e7cab6508660d7c3204ae716ee2c5ce4eb9626fd1489cf2fa7645d789bc3b704f8c3ccb04a532a50b"; };
"abbrev@npm:1.1.1" = { filename = "abbrev-npm-1.1.1-3659247eab-a4a97ec07d.zip"; sha512 = "a4a97ec07d7ea112c517036882b2ac22f3109b7b19077dc656316d07d308438aac28e4d9746dc4d84bf6b1e75b4a7b0a5f3cb30592419f128ca9a8cee3bcfa17"; };
"isexe@npm:2.0.0" = { filename = "isexe-npm-2.0.0-b58870bd2e-26bf6c5480.zip"; sha512 = "26bf6c5480dda5161c820c5b5c751ae1e766c587b1f951ea3fcfc973bafb7831ae5b54a31a69bd670220e42e99ec154475025a468eae58ea262f813fdc8d1c62"; };
"@babel/helper-string-parser@npm:7.21.5" = { filename = "@babel-helper-string-parser-npm-7.21.5-9fa0e56f04-36c0ded452.zip"; sha512 = "36c0ded452f3858e67634b81960d4bde1d1cd2a56b82f4ba2926e97864816021c885f111a7cf81de88a0ed025f49d84a393256700e9acbca2d99462d648705d8"; };
"@juggle/resize-observer@npm:3.4.0" = { filename = "@juggle-resize-observer-npm-3.4.0-659544c6b5-2505028c05.zip"; sha512 = "2505028c05cc2e17639fcad06218b1c4b60f932a4ebb4b41ab546ef8c157031ae377e3f560903801f6d01706dbefd4943b6c4704bf19ed86dfa1c62f1473a570"; };
"glob@npm:7.2.0" = { filename = "glob-npm-7.2.0-bb4644d239-78a8ea9423.zip"; sha512 = "78a8ea942331f08ed2e055cb5b9e40fe6f46f579d7fd3d694f3412fe5db23223d29b7fee1575440202e9a7ff9a72ab106a39fee39934c7bedafe5e5f8ae20134"; };
"lru-cache@npm:6.0.0" = { filename = "lru-cache-npm-6.0.0-b4c8668fe1-f97f499f89.zip"; sha512 = "f97f499f898f23e4585742138a22f22526254fdba6d75d41a1c2526b3b6cc5747ef59c5612ba7375f42aca4f8461950e925ba08c991ead0651b4918b7c978297"; };
"tar@npm:6.1.11" = { filename = "tar-npm-6.1.11-e6ac3cba9c-a04c07bb9e.zip"; sha512 = "a04c07bb9e2d8f46776517d4618f2406fb977a74d914ad98b264fc3db0fe8224da5bec11e5f8902c5b9bcb8ace22d95fbe3c7b36b8593b7dfc8391a25898f32f"; };
"@jridgewell/trace-mapping@npm:0.3.15" = { filename = "@jridgewell-trace-mapping-npm-0.3.15-7357dbf648-38917e9c2b.zip"; sha512 = "38917e9c2b014d469a9f51c016ed506acbe44dd16ec2f6f99b553ebf3764d22abadbf992f2367b6d2b3511f3eae8ed3a8963f6c1030093fda23efd35ecab2bae"; };
"@babel/highlight@npm:7.18.6" = { filename = "@babel-highlight-npm-7.18.6-9d35ad2e27-92d8ee6154.zip"; sha512 = "92d8ee61549de5ff5120e945e774728e5ccd57fd3b2ed6eace020ec744823d4a98e242be1453d21764a30a14769ecd62170fba28539b211799bbaf232bbb2789"; };
"jsesc@npm:2.5.2" = { filename = "jsesc-npm-2.5.2-c5acb78804-4dc1907711.zip"; sha512 = "4dc190771129e12023f729ce20e1e0bfceac84d73a85bc3119f7f938843fe25a4aeccb54b6494dce26fcf263d815f5f31acdefac7cc9329efb8422a4f4d9fa9d"; };
"@babel/helper-module-transforms@npm:7.21.5" = { filename = "@babel-helper-module-transforms-npm-7.21.5-f21e36f6a3-1ccfc88830.zip"; sha512 = "1ccfc88830675a5d485d198e918498f9683cdd46f973fdd4fe1c85b99648fb70f87fca07756c7a05dc201bd9b248c74ced06ea80c9991926ac889f53c3659675"; };
"@babel/code-frame@npm:7.18.6" = { filename = "@babel-code-frame-npm-7.18.6-25229a7e34-195e2be317.zip"; sha512 = "195e2be3172d7684bf95cff69ae3b7a15a9841ea9d27d3c843662d50cdd7d6470fd9c8e64be84d031117e4a4083486effba39f9aef6bbb2c89f7f21bcfba33ba"; };
"@babel/helper-replace-supers@npm:7.21.5" = { filename = "@babel-helper-replace-supers-npm-7.21.5-dee5836977-4fd343e6f9.zip"; sha512 = "4fd343e6f90533743d8e8a1f42e50377b3d6b27f524a27eb97ff28f075e4e55cca2383adb1b0973de358b08022aef0fec4c8d69711e1da43bf9b887b5a893677"; };
"globals@npm:11.12.0" = { filename = "globals-npm-11.12.0-1fa7f41a6c-67051a45ec.zip"; sha512 = "67051a45eca3db904aee189dfc7cd53c20c7d881679c93f6146ddd4c9f4ab2268e68a919df740d39c71f4445d2b38ee360fc234428baea1dbdfe68bbcb46979e"; };
"vdirs@npm:0.1.7" = { filename = "vdirs-npm-0.1.7-4af80fca17-4a1027ab31.zip"; sha512 = "4a1027ab319e1bab9c27b5bd62e930fbc56fc023b5f3233c35173dd34ccd4f7862c46232b9f22067178de9a6dd1cee9d9f02311c49cc538bbb2ee7b2d1512776"; };
"is-number@npm:7.0.0" = { filename = "is-number-npm-7.0.0-060086935c-456ac6f8e0.zip"; sha512 = "456ac6f8e0f3111ed34668a624e45315201dff921e5ac181f8ec24923b99e9f32ca1a194912dc79d539c97d33dba17dc635202ff0b2cf98326f608323276d27a"; };
"@esbuild/win32-x64@npm:0.18.20" = { filename = "@esbuild-win32-x64-npm-0.18.20-37a9ab2bda-8.zip"; sha512 = "c70427c5b70b79e3ab0aefb781bb55abbb392998806da7775dc78c8c3909e0994278bf0c7fe5c543f4987e2d507e1e9326b3d032340b7a3e1b059bc0e48cd63e"; };
"@jridgewell/gen-mapping@npm:0.3.3" = { filename = "@jridgewell-gen-mapping-npm-0.3.3-1815eba94c-4a74944bd3.zip"; sha512 = "4a74944bd31f22354fc01c3da32e83c19e519e3bbadafa114f6da4522ea77dd0c2842607e923a591d60a76699d819a2fbb6f3552e277efdb9b58b081390b60ab"; };
"@babel/compat-data@npm:7.21.7" = { filename = "@babel-compat-data-npm-7.21.7-62e7f604b1-28747eb3fc.zip"; sha512 = "28747eb3fc084d088ba2db0336f52118cfa730a57bdbac81630cae1f38ad0336605b95b3390325937802f344e0b7fa25e2f1b67e3ee2d7383b877f88dee0e51c"; };
"@babel/helper-validator-option@npm:7.21.0" = { filename = "@babel-helper-validator-option-npm-7.21.0-fbe86866e3-8ece4c78ff.zip"; sha512 = "8ece4c78ffa5461fd8ab6b6e57cc51afad59df08192ed5d84b475af4a7193fc1cb794b59e3e7be64f3cdc4df7ac78bf3dbb20c129d7757ae078e6279ff8c2f07"; };
"@babel/highlight@npm:7.16.10" = { filename = "@babel-highlight-npm-7.16.10-626c03326c-1f1bdd752a.zip"; sha512 = "1f1bdd752a90844f4efc22166a46303fb651ba0fd75a06daba3ebae2575ab3edc1da9827c279872a3aaf305f50a18473c5fa1966752726a2b253065fd4c0745e"; };
"@babel/helper-environment-visitor@npm:7.16.7" = { filename = "@babel-helper-environment-visitor-npm-7.16.7-3ee2ba2019-c03a10105d.zip"; sha512 = "c03a10105d9ebd1fe632a77356b2e6e2f3c44edba9a93b0dc3591b6a66bd7a2e323dd9502f9ce96fc6401234abff1907aa877b6674f7826b61c953f7c8204bbe"; };
"@babel/helper-hoist-variables@npm:7.16.7" = { filename = "@babel-helper-hoist-variables-npm-7.16.7-25cc3abba4-6ae1641f4a.zip"; sha512 = "6ae1641f4a751cd9045346e3f61c3d9ec1312fd779ab6d6fecfe2a96e59a481ad5d7e40d2a840894c13b3fd6114345b157f9e3062fc5f1580f284636e722de60"; };
"@babel/helper-split-export-declaration@npm:7.16.7" = { filename = "@babel-helper-split-export-declaration-npm-7.16.7-5b9ae90171-e10aaf1354.zip"; sha512 = "e10aaf135465c55114627951b79115f24bc7af72ecbb58d541d66daf1edaee5dde7cae3ec8c3639afaf74526c03ae3ce723444e3b5b3dc77140c456cd84bcaa1"; };
"dom-serializer@npm:2.0.0" = { filename = "dom-serializer-npm-2.0.0-378ebc7200-cd1810544f.zip"; sha512 = "cd1810544fd8cdfbd51fa2c0c1128ec3a13ba92f14e61b7650b5de421b88205fd2e3f0cc6ace82f13334114addb90ed1c2f23074a51770a8e9c1273acbc7f3e6"; };
"console-control-strings@npm:1.1.0" = { filename = "console-control-strings-npm-1.1.0-e3160e5275-8755d76787.zip"; sha512 = "8755d76787f94e6cf79ce4666f0c5519906d7f5b02d4b884cf41e11dcd759ed69c57da0670afd9236d229a46e0f9cf519db0cd829c6dca820bb5a5c3def584ed"; };
"set-blocking@npm:2.0.0" = { filename = "set-blocking-npm-2.0.0-49e2cffa24-6e65a05f7c.zip"; sha512 = "6e65a05f7cf7ebdf8b7c75b101e18c0b7e3dff4940d480efed8aad3a36a4005140b660fa1d804cb8bce911cac290441dc728084a30504d3516ac2ff7ad607b02"; };
"@jridgewell/trace-mapping@npm:0.3.18" = { filename = "@jridgewell-trace-mapping-npm-0.3.18-cd96571385-0572669f85.zip"; sha512 = "0572669f855260808c16fe8f78f5f1b4356463b11d3f2c7c0b5580c8ba1cbf4ae53efe9f627595830856e57dbac2325ac17eb0c3dd0ec42102e6f227cc289c02"; };
"lru-cache@npm:5.1.1" = { filename = "lru-cache-npm-5.1.1-f475882a51-c154ae1cbb.zip"; sha512 = "c154ae1cbb0c2206d1501a0e94df349653c92c8cbb25236d7e85190bcaf4567a03ac6eb43166fabfa36fd35623694da7233e88d9601fbf411a9a481d85dbd2cb"; };
"@babel/traverse@npm:7.21.5" = { filename = "@babel-traverse-npm-7.21.5-1ca322a4d6-b403733fa7.zip"; sha512 = "b403733fa7d858f0c8e224f0434a6ade641bc469a4f92975363391e796629d5bf53e544761dfe85039aab92d5389ebe7721edb309d7a5bb7df2bf74f37bf9f47"; };
"@jridgewell/gen-mapping@npm:0.3.2" = { filename = "@jridgewell-gen-mapping-npm-0.3.2-c64eeb4a4e-1832707a1c.zip"; sha512 = "1832707a1c476afebe4d0fbbd4b9434fdb51a4c3e009ab1e9938648e21b7a97049fa6009393bdf05cab7504108413441df26d8a3c12193996e65493a4efb6882"; };
"@babel/generator@npm:7.16.8" = { filename = "@babel-generator-npm-7.16.8-f9d7f9b832-83af38b347.zip"; sha512 = "83af38b34735605c9d5f774c87a46c2cffaf666b28e9eeba883b2d7076412257e5c2264c26d9740ce44da6955fdaf857659391db02c012714a2a6dc19e403105"; };
"@babel/helper-function-name@npm:7.16.7" = { filename = "@babel-helper-function-name-npm-7.16.7-aa24c7b296-fc77cbe7b1.zip"; sha512 = "fc77cbe7b10cfa2a262d7a37dca575c037f20419dfe0c5d9317f589599ca24beb5f5c1057748011159149eaec47fe32338c6c6412376fcded68200df470161e1"; };
"fs.realpath@npm:1.0.0" = { filename = "fs.realpath-npm-1.0.0-c8f05d8126-99ddea01a7.zip"; sha512 = "99ddea01a7e75aa276c250a04eedeffe5662bce66c65c07164ad6264f9de18fb21be9433ead460e54cff20e31721c811f4fb5d70591799df5f85dce6d6746fd0"; };
"inherits@npm:2.0.4" = { filename = "inherits-npm-2.0.4-c66b3957a0-4a48a73384.zip"; sha512 = "4a48a733847879d6cf6691860a6b1e3f0f4754176e4d71494c41f3475553768b10f84b5ce1d40fbd0e34e6bfbb864ee35858ad4dd2cf31e02fc4a154b724d7f1"; };
"path-is-absolute@npm:1.0.1" = { filename = "path-is-absolute-npm-1.0.1-31bc695ffd-060840f92c.zip"; sha512 = "060840f92cf8effa293bcc1bea81281bd7d363731d214cbe5c227df207c34cd727430f70c6037b5159c8a870b9157cba65e775446b0ab06fd5ecc7e54615a3b8"; };
"are-we-there-yet@npm:2.0.0" = { filename = "are-we-there-yet-npm-2.0.0-7d2f5201ce-6c80b4fd04.zip"; sha512 = "6c80b4fd04ecee6ba6e737e0b72a4b41bdc64b7d279edfc998678567ff583c8df27e27523bc789f2c99be603ffa9eaa612803da1d886962d2086e7ff6fa90c7c"; };
"yallist@npm:4.0.0" = { filename = "yallist-npm-4.0.0-b493d9e907-343617202a.zip"; sha512 = "343617202af32df2a15a3be36a5a8c0c8545208f3d3dfbc6bb7c3e3b7e8c6f8e7485432e4f3b88da3031a6e20afa7c711eded32ddfb122896ac5d914e75848d5"; };
"chownr@npm:2.0.0" = { filename = "chownr-npm-2.0.0-638f1c9c61-c57cf9dd07.zip"; sha512 = "c57cf9dd0791e2f18a5ee9c1a299ae6e801ff58fee96dc8bfd0dcb4738a6ce58dd252a3605b1c93c6418fe4f9d5093b28ffbf4d66648cb2a9c67eaef9679be2f"; };
"mkdirp@npm:1.0.4" = { filename = "mkdirp-npm-1.0.4-37f6ef56b9-a96865108c.zip"; sha512 = "a96865108c6c3b1b8e1d5e9f11843de1e077e57737602de1b82030815f311be11f96f09cce59bd5b903d0b29834733e5313f9301e3ed6d6f6fba2eae0df4298f"; };
"@jridgewell/resolve-uri@npm:3.0.5" = { filename = "@jridgewell-resolve-uri-npm-3.0.5-bb57d127db-1ee652b693.zip"; sha512 = "1ee652b693da7979ac4007926cc3f0a32b657ffeb913e111f44e5b67153d94a2f28a1d560101cc0cf8087625468293a69a00f634a2914e1a6d0817ba2039a913"; };
"@jridgewell/sourcemap-codec@npm:1.4.11" = { filename = "@jridgewell-sourcemap-codec-npm-1.4.11-68fac44d63-3b2afaf840.zip"; sha512 = "3b2afaf8400fb07a36db60e901fcce6a746cdec587310ee9035939d89878e57b2dec8173b0b8f63176f647efa352294049a53c49739098eb907ff81fec2547c8"; };
"js-tokens@npm:4.0.0" = { filename = "js-tokens-npm-4.0.0-0ac852e9e2-8a95213a5a.zip"; sha512 = "8a95213a5a77deb6cbe94d86340e8d9ace2b93bc367790b260101d2f36a2eaf4e4e22d9fa9cf459b38af3a32fb4190e638024cf82ec95ef708680e405ea7cc78"; };
"minimatch@npm:3.0.4" = { filename = "minimatch-npm-3.0.4-6e76f51c23-66ac295f8a.zip"; sha512 = "66ac295f8a7b59788000ea3749938b0970344c841750abd96694f80269b926ebcafad3deeb3f1da2522978b119e6ae3a5869b63b13a7859a456b3408bd18a078"; };
"once@npm:1.4.0" = { filename = "once-npm-1.4.0-ccf03ef07a-cd0a885013.zip"; sha512 = "cd0a88501333edd640d95f0d2700fbde6bff20b3d4d9bdc521bdd31af0656b5706570d6c6afe532045a20bb8dc0849f8332d6f2a416e0ba6d3d3b98806c7db68"; };
"fs-minipass@npm:2.1.0" = { filename = "fs-minipass-npm-2.1.0-501ef87306-1b8d128dae.zip"; sha512 = "1b8d128dae2ac6cc94230cc5ead341ba3e0efaef82dab46a33d171c044caaa6ca001364178d42069b2809c35a1c3c35079a32107c770e9ffab3901b59af8c8b1"; };
"minipass@npm:3.1.6" = { filename = "minipass-npm-3.1.6-f032df1661-57a0404141.zip"; sha512 = "57a04041413a3531a65062452cb5175f93383ef245d6f4a2961d34386eb9aa8ac11ac7f16f791f5e8bbaf1dfb1ef01596870c88e8822215db57aa591a5bb0a77"; };
"@jridgewell/set-array@npm:1.1.2" = { filename = "@jridgewell-set-array-npm-1.1.2-45b82d7fb6-69a84d5980.zip"; sha512 = "69a84d5980385f396ff60a175f7177af0b8da4ddb81824cb7016a9ef914eee9806c72b6b65942003c63f7983d4f39a5c6c27185bbca88eb4690b62075602e28e"; };
"browserslist@npm:4.21.4" = { filename = "browserslist-npm-4.21.4-7d64a96afc-4af3793704.zip"; sha512 = "4af3793704dbb4615bcd29059ab472344dc7961c8680aa6c4bb84f05340e14038d06a5aead58724eae69455b8fade8b8c69f1638016e87e5578969d74c078b79"; };
"@babel/helper-module-imports@npm:7.21.4" = { filename = "@babel-helper-module-imports-npm-7.21.4-e4cd6b4e21-bd330a2eda.zip"; sha512 = "bd330a2edaafeb281fbcd9357652f8d2666502567c0aad71db926e8499c773c9ea9c10dfaae30122452940326d90c8caff5c649ed8e1bf15b23f858758d3abc6"; };
"@babel/helper-simple-access@npm:7.21.5" = { filename = "@babel-helper-simple-access-npm-7.21.5-adbdd3a62b-ad212beaa2.zip"; sha512 = "ad212beaa24be3864c8c95bee02f840222457ccf5419991e2d3e3e39b0f75b77e7e857e0bf4ed428b1cd97acefc87f3831bdb0b9696d5ad0557421f398334fc3"; };
"entities@npm:4.5.0" = { filename = "entities-npm-4.5.0-7cdb83b832-853f8ebd5b.zip"; sha512 = "853f8ebd5b425d350bffa97dd6958143179a5938352ccae092c62d1267c4e392a039be1bae7d51b6e4ffad25f51f9617531fedf5237f15df302ccfb452cbf2d7"; };
"inflight@npm:1.0.6" = { filename = "inflight-npm-1.0.6-ccedb4b908-f4f76aa072.zip"; sha512 = "f4f76aa072ce19fae87ce1ef7d221e709afb59d445e05d47fba710e85470923a75de35bfae47da6de1b18afc3ce83d70facf44cfb0aff89f0a3f45c0a0244dfd"; };
"minizlib@npm:2.1.2" = { filename = "minizlib-npm-2.1.2-ea89cd0cfb-f1fdeac0b0.zip"; sha512 = "f1fdeac0b07cf8f30fcf12f4b586795b97be856edea22b5e9072707be51fc95d41487faec3f265b42973a304fe3a64acd91a44a3826a963e37b37bafde0212c3"; };
"@jridgewell/resolve-uri@npm:3.1.0" = { filename = "@jridgewell-resolve-uri-npm-3.1.0-6ff2351e61-b5ceaaf9a1.zip"; sha512 = "b5ceaaf9a110fcb2780d1d8f8d4a0bfd216702f31c988d8042e5f8fbe353c55d9b0f55a1733afdc64806f8e79c485d2464680ac48a0d9fcadb9548ee6b81d267"; };
"@jridgewell/sourcemap-codec@npm:1.4.14" = { filename = "@jridgewell-sourcemap-codec-npm-1.4.14-f5f0630788-61100637b6.zip"; sha512 = "61100637b6d173d3ba786a5dff019e1a74b1f394f323c1fee337ff390239f053b87266c7a948777f4b1ee68c01a8ad0ab61e5ff4abb5a012a0b091bec391ab97"; };
"yallist@npm:3.1.1" = { filename = "yallist-npm-3.1.1-a568a556b4-48f7bb00dc.zip"; sha512 = "48f7bb00dc19fc635a13a39fe547f527b10c9290e7b3e836b9a8f1ca04d4d342e85714416b3c2ab74949c9c66f9cebb0473e6bc353b79035356103b47641285d"; };
"chalk@npm:2.4.2" = { filename = "chalk-npm-2.4.2-3ea16dd91e-ec3661d38f.zip"; sha512 = "ec3661d38fe77f681200f878edbd9448821924e0f93a9cefc0e26a33b145f1027a2084bf19967160d11e1f03bfe4eaffcabf5493b89098b2782c3fe0b03d80c2"; };
"@babel/helper-hoist-variables@npm:7.18.6" = { filename = "@babel-helper-hoist-variables-npm-7.18.6-6eb061f405-fd9c35bb43.zip"; sha512 = "fd9c35bb435fda802bf9ff7b6f2df06308a21277c6dec2120a35b09f9de68f68a33972e2c15505c1a1a04b36ec64c9ace97d4a9e26d6097b76b4396b7c5fa20f"; };
"source-map@npm:0.5.7" = { filename = "source-map-npm-0.5.7-7c3f035429-5dc2043b93.zip"; sha512 = "5dc2043b93d2f194142c7f38f74a24670cd7a0063acdaf4bf01d2964b402257ae843c2a8fa822ad5b71013b5fcafa55af7421383da919752f22ff488bc553f4d"; };
"delegates@npm:1.0.0" = { filename = "delegates-npm-1.0.0-9b1942d75f-a51744d9b5.zip"; sha512 = "a51744d9b53c164ba9c0492471a1a2ffa0b6727451bdc89e31627fdf4adda9d51277cfcbfb20f0a6f08ccb3c436f341df3e92631a3440226d93a8971724771fd"; };
"@babel/helper-get-function-arity@npm:7.16.7" = { filename = "@babel-helper-get-function-arity-npm-7.16.7-987b1b1bed-25d969fb20.zip"; sha512 = "25d969fb207ff2ad5f57a90d118f6c42d56a0171022e200aaa919ba7dc95ae7f92ec71cdea6c63ef3629a0dc962ab4c78e09ca2b437185ab44539193f796e0c3"; };
"wrappy@npm:1.0.2" = { filename = "wrappy-npm-1.0.2-916de4d4b3-159da4805f.zip"; sha512 = "159da4805f7e84a3d003d8841557196034155008f817172d4e986bd591f74aa82aa7db55929a54222309e01079a65a92a9e6414da5a6aa4b01ee44a511ac3ee5"; };
"caniuse-lite@npm:1.0.30001408" = { filename = "caniuse-lite-npm-1.0.30001408-e7a281ba63-9d741df8e3.zip"; sha512 = "9d741df8e3d6d22473d7c66bb4d9c47ad21693ff507723faf9c97584b63063ef513245e439972beca30c4b171d3204a8fff678703be3516aa511403cf6b02a54"; };
"electron-to-chromium@npm:1.4.256" = { filename = "electron-to-chromium-npm-1.4.256-53478c2d69-878ca8e33a.zip"; sha512 = "878ca8e33a05165808a662b52ac332a42a5fcf842540de38c4cdde462e4c2cb2f2c10c4864cd44c486f8470f88818f42d275774865666aad424e1e4f500d91e8"; };
"node-releases@npm:2.0.6" = { filename = "node-releases-npm-2.0.6-8accb3fefb-e86a926dc9.zip"; sha512 = "e86a926dc9fbb3b41b4c4a89d998afdf140e20a4e8dbe6c0a807f7b2948b42ea97d7fd3ad4868041487b6e9ee98409829c6e4d84a734a4215dff060a7fbeb4bf"; };
"make-fetch-happen@npm:9.1.0" = { filename = "make-fetch-happen-npm-9.1.0-23184ad7f6-0eb371c85f.zip"; sha512 = "0eb371c85fdd0b1584fcfdf3dc3c62395761b3c14658be02620c310305a9a7ecf1617a5e6fb30c1d081c5c8aaf177fa133ee225024313afabb7aa6a10f1e3d04"; };
"brace-expansion@npm:1.1.11" = { filename = "brace-expansion-npm-1.1.11-fb95eb05ad-faf34a7bb0.zip"; sha512 = "faf34a7bb0c3fcf4b59c7808bc5d2a96a40988addf2e7e09dfbb67a2251800e0d14cd2bfc1aa79174f2f5095c54ff27f46fb1289fe2d77dac755b5eb3434cc07"; };
"readable-stream@npm:3.6.0" = { filename = "readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip"; sha512 = "d4ea81502d3799439bb955a3a5d1d808592cf3133350ed352aeaa499647858b27b1c4013984900238b0873ec8d0d8defce72469fb7a83e61d53f5ad61cb80dc8"; };
"gauge@npm:4.0.0" = { filename = "gauge-npm-4.0.0-962bc1259b-637b34c84f.zip"; sha512 = "637b34c84f518defa89319dbef68211a24e9302182ad2a619e3be1be5b7dcf2a962c8359e889294af667440f4722e7e6e61671859e00bd8ec280a136ded89b25"; };
"escape-string-regexp@npm:1.0.5" = { filename = "escape-string-regexp-npm-1.0.5-3284de402f-6092fda75c.zip"; sha512 = "6092fda75c63b110c706b6a9bfde8a612ad595b628f0bd2147eea1d3406723020810e591effc7db1da91d80a71a737a313567c5abb3813e8d9c71f4aa595b410"; };
"update-browserslist-db@npm:1.0.9" = { filename = "update-browserslist-db-npm-1.0.9-b9b06a6669-f625899b23.zip"; sha512 = "f625899b236f6a4d7f62b56be1b8da230c5563d1fef84d3ef148f2e1a3f11a5a4b3be4fd7e3703e51274c116194017775b10afb4de09eb2c0d09d36b90f1f578"; };
"ansi-styles@npm:3.2.1" = { filename = "ansi-styles-npm-3.2.1-8cb8107983-d85ade01c1.zip"; sha512 = "d85ade01c10e5dd77b6c89f34ed7531da5830d2cb5882c645f330079975b716438cd7ebb81d0d6e6b4f9c577f19ae41ab55f07f19786b02f9dfd9e0377395665"; };
"supports-color@npm:5.5.0" = { filename = "supports-color-npm-5.5.0-183ac537bc-95f6f4ba5a.zip"; sha512 = "95f6f4ba5afdf92f495b5a912d4abee8dcba766ae719b975c56c084f5004845f6f5a5f7769f52d53f40e21952a6d87411bafe34af4a01e65f9926002e38e1dac"; };
"http-cache-semantics@npm:4.1.0" = { filename = "http-cache-semantics-npm-4.1.0-860520a31f-974de94a81.zip"; sha512 = "974de94a81c5474be07f269f9fd8383e92ebb5a448208223bfb39e172a9dbc26feff250192ecc23b9593b3f92098e010406b0f24bd4d588d631f80214648ed42"; };
"is-lambda@npm:1.0.1" = { filename = "is-lambda-npm-1.0.1-7ab55bc8a8-93a32f0194.zip"; sha512 = "93a32f01940220532e5948538699ad610d5924ac86093fcee83022252b363eb0cc99ba53ab084a04e4fb62bf7b5731f55496257a4c38adf87af9c4d352c71c35"; };
"negotiator@npm:0.6.3" = { filename = "negotiator-npm-0.6.3-9d50e36171-b8ffeb1e26.zip"; sha512 = "b8ffeb1e262eff7968fc90a2b6767b04cfd9842582a9d0ece0af7049537266e7b2506dfb1d107a32f06dd849ab2aea834d5830f7f4d0e5cb7d36e1ae55d021d9"; };
"balanced-match@npm:1.0.2" = { filename = "balanced-match-npm-1.0.2-a53c126459-9706c088a2.zip"; sha512 = "9706c088a283058a8a99e0bf91b0a2f75497f185980d9ffa8b304de1d9e58ebda7c72c07ebf01dadedaac5b2907b2c6f566f660d62bd336c3468e960403b9d65"; };
"concat-map@npm:0.0.1" = { filename = "concat-map-npm-0.0.1-85a921b7ee-902a9f5d89.zip"; sha512 = "902a9f5d8967a3e2faf138d5cb784b9979bad2e6db5357c5b21c568df4ebe62bcb15108af1b2253744844eb964fc023fbd9afbbbb6ddd0bcc204c6fb5b7bf3af"; };
"minipass-collect@npm:1.0.2" = { filename = "minipass-collect-npm-1.0.2-3b4676eab5-14df761028.zip"; sha512 = "14df761028f3e47293aee72888f2657695ec66bd7d09cae7ad558da30415fdc4752bbfee66287dcc6fd5e6a2fa3466d6c484dc1cbd986525d9393b9523d97f10"; };
"minipass-flush@npm:1.0.5" = { filename = "minipass-flush-npm-1.0.5-efe79d9826-56269a0b22.zip"; sha512 = "56269a0b22bad756a08a94b1ffc36b7c9c5de0735a4dd1ab2b06c066d795cfd1f0ac44a0fcae13eece5589b908ecddc867f04c745c7009be0b566421ea0944cf"; };
"minipass-pipeline@npm:1.2.4" = { filename = "minipass-pipeline-npm-1.2.4-5924cb077f-b14240dac0.zip"; sha512 = "b14240dac0d29823c3d5911c286069e36d0b81173d7bdf07a7e4a91ecdef92cdff4baaf31ea3746f1c61e0957f652e641223970870e2353593f382112257971b"; };
"ssri@npm:8.0.1" = { filename = "ssri-npm-8.0.1-a369e72ce2-bc447f5af8.zip"; sha512 = "bc447f5af814fa9713aa201ec2522208ae0f4d8f3bda7a1f445a797c7b929a02720436ff7c478fb5edc4045adb02b1b88d2341b436a80798734e2494f1067b36"; };
"util-deprecate@npm:1.0.2" = { filename = "util-deprecate-npm-1.0.2-e3fe1a219c-474acf1146.zip"; sha512 = "474acf1146cb2701fe3b074892217553dfcf9a031280919ba1b8d651a068c9b15d863b7303cb15bd00a862b498e6cf4ad7b4a08fb134edd5a6f7641681cb54a2"; };
"ansi-regex@npm:5.0.1" = { filename = "ansi-regex-npm-5.0.1-c963a48615-2aa4bb54ca.zip"; sha512 = "2aa4bb54caf2d622f1afdad09441695af2a83aa3fe8b8afa581d205e57ed4261c183c4d3877cee25794443fde5876417d859c108078ab788d6af7e4fe52eb66b"; };
"aproba@npm:2.0.0" = { filename = "aproba-npm-2.0.0-8716bcfde6-5615cadcfb.zip"; sha512 = "5615cadcfb45289eea63f8afd064ab656006361020e1735112e346593856f87435e02d8dcc7ff0d11928bc7d425f27bc7c2a84f6c0b35ab0ff659c814c138a24"; };
"color-support@npm:1.1.3" = { filename = "color-support-npm-1.1.3-3be5c53455-9b73568176.zip"; sha512 = "9b7356817670b9a13a26ca5af1c21615463b500783b739b7634a0c2047c16cef4b2865d7576875c31c3cddf9dd621fa19285e628f20198b233a5cfdda6d0793b"; };
"has-unicode@npm:2.0.1" = { filename = "has-unicode-npm-2.0.1-893adb4747-1eab07a743.zip"; sha512 = "1eab07a7436512db0be40a710b29b5dc21fa04880b7f63c9980b706683127e3c1b57cb80ea96d47991bdae2dfe479604f6a1ba410106ee1046a41d1bd0814400"; };
"signal-exit@npm:3.0.6" = { filename = "signal-exit-npm-3.0.6-66fc2466b6-b819ac81ba.zip"; sha512 = "b819ac81ba757af559dad0804233ae31bf6f054591cd8a671e9cbcf09f21c72ec3076fe87d1e04861f5b33b47d63f0694b568de99c99cd733ee2060515beb6d5"; };
"escalade@npm:3.1.1" = { filename = "escalade-npm-3.1.1-e02da076aa-a3e2a99f07.zip"; sha512 = "a3e2a99f07acb74b3ad4989c48ca0c3140f69f923e56d0cba0526240ee470b91010f9d39001f2a4a313841d237ede70a729e92125191ba5d21e74b106800b133"; };
"https-proxy-agent@npm:5.0.0" = { filename = "https-proxy-agent-npm-5.0.0-bb777903c3-165bfb090b.zip"; sha512 = "165bfb090bd26d47693597661298006841ab733d0c7383a8cb2f17373387a94c903a3ac687090aa739de05e379ab6f868bae84ab4eac288ad85c328cd1ec9e53"; };
"promise-retry@npm:2.0.1" = { filename = "promise-retry-npm-2.0.1-871f0b01b7-f96a3f6d90.zip"; sha512 = "f96a3f6d90b92b568a26f71e966cbbc0f63ab85ea6ff6c81284dc869b41510e6cdef99b6b65f9030f0db422bf7c96652a3fff9f2e8fb4a0f069d8f4430359429"; };
"string_decoder@npm:1.3.0" = { filename = "string_decoder-npm-1.3.0-2422117fd0-8417646695.zip"; sha512 = "8417646695a66e73aefc4420eb3b84cc9ffd89572861fe004e6aeb13c7bc00e2f616247505d2dbbef24247c372f70268f594af7126f43548565c68c117bdeb56"; };
"strip-ansi@npm:6.0.1" = { filename = "strip-ansi-npm-6.0.1-caddc7cb40-f3cd25890a.zip"; sha512 = "f3cd25890aef3ba6e1a74e20896c21a46f482e93df4a06567cebf2b57edabb15133f1f94e57434e0a958d61186087b1008e89c94875d019910a213181a14fc8c"; };
"wide-align@npm:1.1.5" = { filename = "wide-align-npm-1.1.5-889d77e592-d5fc37cd56.zip"; sha512 = "d5fc37cd561f9daee3c80e03b92ed3e84d80dde3365a8767263d03dacfc8fa06b065ffe1df00d8c2a09f731482fcacae745abfbb478d4af36d0a891fad4834d3"; };
"has-flag@npm:3.0.0" = { filename = "has-flag-npm-3.0.0-16ac11fe05-4a15638b45.zip"; sha512 = "4a15638b454bf086c8148979aae044dd6e39d63904cd452d970374fa6a87623423da485dfb814e7be882e05c096a7ccf1ebd48e7e7501d0208d8384ff4dea73b"; };
"agentkeepalive@npm:4.2.0" = { filename = "agentkeepalive-npm-4.2.0-e5e72b8ce4-89806f83ce.zip"; sha512 = "89806f83ceebbcaabf6bd581a8dce4870910fd2a11f66df8f505b4cd4ce4ca5ab9e6eec8d11ce8531a6b60f6748b75b0775e0e2fa33871503ef00d535418a19a"; };
"http-proxy-agent@npm:4.0.1" = { filename = "http-proxy-agent-npm-4.0.1-ce9ef61788-c6a5da5a19.zip"; sha512 = "c6a5da5a1929416b6bbdf77b1aca13888013fe7eb9d59fc292e25d18e041bb154a8dfada58e223fc7b76b9b2d155a87e92e608235201f77d34aa258707963a82"; };
"socks-proxy-agent@npm:6.1.1" = { filename = "socks-proxy-agent-npm-6.1.1-a3843946ba-9a8a4f791b.zip"; sha512 = "9a8a4f791bba0060315cf7291ca6f9db37d6fc280fd0860d73d8887d3efe4c22e823aa25a8d5375f6079279f8dc91b50c075345179bf832bfe3c7c26d3582e3c"; };
"color-convert@npm:1.9.3" = { filename = "color-convert-npm-1.9.3-1fe690075e-fd7a64a17c.zip"; sha512 = "fd7a64a17cde98fb923b1dd05c5f2e6f7aefda1b60d67e8d449f9328b4e53b228a428fd38bfeaeb2db2ff6b6503a776a996150b80cdf224062af08a5c8a3a203"; };
"minipass-fetch@npm:1.4.1" = { filename = "minipass-fetch-npm-1.4.1-2d67357feb-ec93697bdb.zip"; sha512 = "ec93697bdb62129c4e6c0104138e681e30efef8c15d9429dd172f776f83898471bc76521b539ff913248cc2aa6d2b37b652c993504a51cc53282563640f29216"; };
"string-width@npm:4.2.3" = { filename = "string-width-npm-4.2.3-2c27177bae-e52c10dc3f.zip"; sha512 = "e52c10dc3fbfcd6c3a15f159f54a90024241d0f149cf8aed2982a2d801d2e64df0bf1dc351cf8e95c3319323f9f220c16e740b06faecd53e2462df1d2b5443fb"; };
"err-code@npm:2.0.3" = { filename = "err-code-npm-2.0.3-082e0ff9a7-8b7b1be20d.zip"; sha512 = "8b7b1be20d2de12d2255c0bc2ca638b7af5171142693299416e6a9339bd7d88fc8d7707d913d78e0993176005405a236b066b45666b27b797252c771156ace54"; };
"retry@npm:0.12.0" = { filename = "retry-npm-0.12.0-72ac7fb4cc-623bd7d2e5.zip"; sha512 = "623bd7d2e5119467ba66202d733ec3c2e2e26568074923bc0585b6b99db14f357e79bdedb63cab56cec47491c4a0da7e6021a7465ca6dc4f481d3898fdd3158c"; };
"safe-buffer@npm:5.2.1" = { filename = "safe-buffer-npm-5.2.1-3481c8aa9b-b99c4b41fd.zip"; sha512 = "b99c4b41fdd67a6aaf280fcd05e9ffb0813654894223afb78a31f14a19ad220bba8aba1cb14eddce1fcfb037155fe6de4e861784eb434f7d11ed58d1e70dd491"; };
"depd@npm:1.1.2" = { filename = "depd-npm-1.1.2-b0c8414da7-6b406620d2.zip"; sha512 = "6b406620d269619852885ce15965272b829df6f409724415e0002c8632ab6a8c0a08ec1f0bd2add05dc7bd7507606f7e2cc034fa24224ab829580040b835ecd9"; };
"@tootallnate/once@npm:1.1.2" = { filename = "@tootallnate-once-npm-1.1.2-0517220057-e1fb1bbbc1.zip"; sha512 = "e1fb1bbbc12089a0cb9433dc290f97bddd062deadb6178ce9bcb93bb7c1aecde5e60184bc7065aec42fe1663622a213493c48bbd4972d931aae48315f18e1be9"; };
"agent-base@npm:6.0.2" = { filename = "agent-base-npm-6.0.2-428f325a93-f52b6872cc.zip"; sha512 = "f52b6872cc96fd5f622071b71ef200e01c7c4c454ee68bc9accca90c98cfb39f2810e3e9aa330435835eedc8c23f4f8a15267f67c6e245d2b33757575bdac49d"; };
"color-name@npm:1.1.3" = { filename = "color-name-npm-1.1.3-728b7b5d39-09c5d3e33d.zip"; sha512 = "09c5d3e33d2105850153b14466501f2bfb30324a2f76568a408763a3b7433b0e50e5b4ab1947868e65cb101bb7cb75029553f2c333b6d4b8138a73fcc133d69d"; };
"humanize-ms@npm:1.2.1" = { filename = "humanize-ms-npm-1.2.1-e942bd7329-9c7a74a282.zip"; sha512 = "9c7a74a2827f9294c009266c82031030eae811ca87b0da3dceb8d6071b9bde22c9f3daef0469c3c533cc67a97d8a167cd9fc0389350e5f415f61a79b171ded16"; };
"emoji-regex@npm:8.0.0" = { filename = "emoji-regex-npm-8.0.0-213764015c-d4c5c39d5a.zip"; sha512 = "d4c5c39d5a9868b5fa152f00cada8a936868fd3367f33f71be515ecee4c803132d11b31a6222b2571b1e5f7e13890156a94880345594d0ce7e3c9895f560f192"; };
"is-fullwidth-code-point@npm:3.0.0" = { filename = "is-fullwidth-code-point-npm-3.0.0-1ecf4ebee5-44a30c2945.zip"; sha512 = "44a30c29457c7fb8f00297bce733f0a64cd22eca270f83e58c105e0d015e45c019491a4ab2faef91ab51d4738c670daff901c799f6a700e27f7314029e99e348"; };
"encoding@npm:0.1.13" = { filename = "encoding-npm-0.1.13-82a1837d30-bb98632f8f.zip"; sha512 = "bb98632f8ffa823996e508ce6a58ffcf5856330fde839ae42c9e1f436cc3b5cc651d4aeae72222916545428e54fd0f6aa8862fd8d25bdbcc4589f1e3f3715e7f"; };
"minipass-sized@npm:1.0.3" = { filename = "minipass-sized-npm-1.0.3-306d86f432-79076749fc.zip"; sha512 = "79076749fcacf21b5d16dd596d32c3b6bf4d6e62abb43868fac21674078505c8b15eaca4e47ed844985a4514854f917d78f588fcd029693709417d8f98b2bd60"; };
"socks@npm:2.6.1" = { filename = "socks-npm-2.6.1-09133d0d22-2ca9d616e4.zip"; sha512 = "2ca9d616e424f645838ebaabb04f85d94ea999e0f8393dc07f86c435af22ed88cb83958feeabd1bb7bc537c635ed47454255635502c6808a6df61af1f41af750"; };
"ms@npm:2.1.3" = { filename = "ms-npm-2.1.3-81ff3cfac1-aa92de6080.zip"; sha512 = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d"; };
"ip@npm:1.1.5" = { filename = "ip-npm-1.1.5-af36318aa6-30133981f0.zip"; sha512 = "30133981f082a060a32644f6a7746e9ba7ac9e2bc07ecc8bbdda3ee8ca9bec1190724c390e45a1ee7695e7edfd2a8f7dda2c104ec5f7ac5068c00648504c7e5a"; };
"smart-buffer@npm:4.2.0" = { filename = "smart-buffer-npm-4.2.0-5ac3f668bb-b5167a7142.zip"; sha512 = "b5167a7142c1da704c0e3af85c402002b597081dd9575031a90b4f229ca5678e9a36e8a374f1814c8156a725d17008ae3bde63b92f9cfd132526379e580bec8b"; };
"iconv-lite@npm:0.6.3" = { filename = "iconv-lite-npm-0.6.3-24b8aae27e-3f60d47a5c.zip"; sha512 = "3f60d47a5c8fc3313317edfd29a00a692cc87a19cac0159e2ce711d0ebc9019064108323b5e493625e25594f11c6236647d8e256fbe7a58f4a3b33b89e6d30bf"; };
"cacache@npm:15.3.0" = { filename = "cacache-npm-15.3.0-a7e5239c6a-a07327c27a.zip"; sha512 = "a07327c27a4152c04eb0a831c63c00390d90f94d51bb80624a66f4e14a6b6360bbf02a84421267bd4d00ca73ac9773287d8d7169e8d2eafe378d2ce140579db8"; };
"safer-buffer@npm:2.1.2" = { filename = "safer-buffer-npm-2.1.2-8d5c0b705e-cab8f25ae6.zip"; sha512 = "cab8f25ae6f1434abee8d80023d7e72b598cf1327164ddab31003c51215526801e40b66c5e65d658a0af1e9d6478cadcb4c745f4bd6751f97d8644786c0978b0"; };
"infer-owner@npm:1.0.4" = { filename = "infer-owner-npm-1.0.4-685ac3d2af-181e732764.zip"; sha512 = "181e732764e4a0611576466b4b87dac338972b839920b2a8cde43642e4ed6bd54dc1fb0b40874728f2a2df9a1b097b8ff83b56d5f8f8e3927f837fdcb47d8a89"; };
"promise-inflight@npm:1.0.1" = { filename = "promise-inflight-npm-1.0.1-5bb925afac-2274948309.zip"; sha512 = "22749483091d2c594261517f4f80e05226d4d5ecc1fc917e1886929da56e22b5718b7f2a75f3807e7a7d471bc3be2907fe92e6e8f373ddf5c64bae35b5af3981"; };
"p-map@npm:4.0.0" = { filename = "p-map-npm-4.0.0-4677ae07c7-cb0ab21ec0.zip"; sha512 = "cb0ab21ec0f32ddffd31dfc250e3afa61e103ef43d957cc45497afe37513634589316de4eb88abdfd969fe6410c22c0b93ab24328833b8eb1ccc087fc0442a1c"; };
"unique-filename@npm:1.1.1" = { filename = "unique-filename-npm-1.1.1-c885c5095b-cf4998c922.zip"; sha512 = "cf4998c9228cc7647ba7814e255dec51be43673903897b1786eff2ac2d670f54d4d733357eb08dea969aa5e6875d0e1bd391d668fbdb5a179744e7c7551a6f80"; };
"@npmcli/fs@npm:1.1.0" = { filename = "@npmcli-fs-npm-1.1.0-fa0ae1b053-e435b883b4.zip"; sha512 = "e435b883b4f8da8c95a820f458cabb7d86582406eed5ad79fc689000d3e2df17e1f475c4903627272c001357cabc70d8b4c62520cbdae8cfab1dfdd51949f408"; };
"@npmcli/move-file@npm:1.1.2" = { filename = "@npmcli-move-file-npm-1.1.2-4f6c7b3354-c96381d4a3.zip"; sha512 = "c96381d4a37448ea280951e46233f7e541058cf57a57d4094dd4bdcaae43fa5872b5f2eb6bfb004591a68e29c5877abe3cdc210cb3588cbf20ab2877f31a7de7"; };
"@gar/promisify@npm:1.1.2" = { filename = "@gar-promisify-npm-1.1.2-2343f94380-d05081e088.zip"; sha512 = "d05081e0887a49c178b75ee3067bd6ee086f73c154d121b854fb2e044e8a89cb1cbb6de3a0dd93a519b80f0531fda68b099dd7256205f7fbb3490324342f2217"; };
"unique-slug@npm:2.0.2" = { filename = "unique-slug-npm-2.0.2-f6ba1ddeb7-5b6876a645.zip"; sha512 = "5b6876a645da08d505dedb970d1571f6cebdf87044cb6b740c8dbb24f0d6e1dc8bdbf46825fd09f994d7cf50760e6f6e063cfa197d51c5902c00a861702eb75a"; };
"aggregate-error@npm:3.1.0" = { filename = "aggregate-error-npm-3.1.0-415a406f4e-1101a33f21.zip"; sha512 = "1101a33f21baa27a2fa8e04b698271e64616b886795fd43c31068c07533c7b3facfcaf4e9e0cab3624bd88f729a592f1c901a1a229c9e490eafce411a8644b79"; };
"imurmurhash@npm:0.1.4" = { filename = "imurmurhash-npm-0.1.4-610c5068a0-7cae75c8cd.zip"; sha512 = "7cae75c8cd9a50f57dadd77482359f659eaebac0319dd9368bcd1714f55e65badd6929ca58569da2b6494ef13fdd5598cd700b1eba23f8b79c5f19d195a3ecf7"; };
"clean-stack@npm:2.2.0" = { filename = "clean-stack-npm-2.2.0-a8ce435a5c-2ac8cd2b2f.zip"; sha512 = "2ac8cd2b2f5ec986a3c743935ec85b07bc174d5421a5efc8017e1f146a1cf5f781ae962618f416352103b32c9cd7e203276e8c28241bbe946160cab16149fb68"; };
"indent-string@npm:4.0.0" = { filename = "indent-string-npm-4.0.0-7b717435b2-824cfb9929.zip"; sha512 = "824cfb9929d031dabf059bebfe08cf3137365e112019086ed3dcff6a0a7b698cb80cf67ccccde0e25b9e2d7527aa6cc1fed1ac490c752162496caba3e6699612"; };
};

in optionalOverride overrideAttrs project
